// <auto-generated />
using System;
using DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBContext.Migrations
{
    [DbContext(typeof(ControlAsistenciaDBContext))]
    [Migration("20220830025721_add-Catalogo-Municipio")]
    partial class addCatalogoMunicipio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControlAsistencia_.Models.Asistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdEmpleado")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("ControlAsistencia_.Models.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adscripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaIngreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Huella")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("IdInmueble")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroExpediente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("ControlAsistencia_.Models.Inmueble", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inmueble");
                });

            modelBuilder.Entity("ControlAsistencia_.Models.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Municipio");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b476639-85d3-4931-9394-3d10b3b40648"),
                            Nombre = "ACAJETE"
                        },
                        new
                        {
                            Id = new Guid("883fd478-e136-4504-a096-1b8d30ab8639"),
                            Nombre = "ACATENO"
                        },
                        new
                        {
                            Id = new Guid("b8c23bfb-5297-4c64-b49d-6bcaa97f1d12"),
                            Nombre = "ACATLAN DE OSORIO"
                        },
                        new
                        {
                            Id = new Guid("0ddfe43e-a48a-4f89-bce3-ce093d05c35f"),
                            Nombre = "ACATZINGO"
                        },
                        new
                        {
                            Id = new Guid("7c58f0ba-3d86-4743-a359-75df6fdbc64f"),
                            Nombre = "AHUAZOTEPEC"
                        },
                        new
                        {
                            Id = new Guid("4b97a0d5-3da2-4a2c-97e5-eb0ed561299d"),
                            Nombre = "AJALPAN"
                        },
                        new
                        {
                            Id = new Guid("0c53a94f-3779-46b9-aa25-1bfe43c046e4"),
                            Nombre = "ALTEPEXI"
                        },
                        new
                        {
                            Id = new Guid("c95ce227-0ffa-4eae-b23e-bdd3c19bc822"),
                            Nombre = "AMOZOC"
                        },
                        new
                        {
                            Id = new Guid("c5c10ff1-a75c-432e-b5df-96086cdfe47b"),
                            Nombre = "ATEMPAN"
                        },
                        new
                        {
                            Id = new Guid("61203fd8-1089-478e-8061-78d51358c7ad"),
                            Nombre = "ATENCINGO"
                        },
                        new
                        {
                            Id = new Guid("0297d60e-31e1-4cb7-973a-a9f9104e7dc9"),
                            Nombre = "ATLIXCO"
                        },
                        new
                        {
                            Id = new Guid("974ec286-e9d0-4ddd-9adb-60e0364c8a9c"),
                            Nombre = "CALPAN"
                        },
                        new
                        {
                            Id = new Guid("f751758f-84ad-43ad-a5d5-b51400ffa92c"),
                            Nombre = "CHALCHICOMULA DE SESMA"
                        },
                        new
                        {
                            Id = new Guid("a4662e9d-4c5b-4fa3-803c-6ab3e0e0b7cc"),
                            Nombre = "CHALCHIHUAPAN"
                        },
                        new
                        {
                            Id = new Guid("76a59c1c-6538-4a5b-9d55-4ed081309a70"),
                            Nombre = "CHIAUTLA DE TAPIA"
                        },
                        new
                        {
                            Id = new Guid("6dc36e6e-8182-4a61-8c1a-83d03d36a673"),
                            Nombre = "CHIETLA"
                        },
                        new
                        {
                            Id = new Guid("796fe037-7c39-48a1-be38-3d883e228409"),
                            Nombre = "CHIGNAHUAPAN"
                        },
                        new
                        {
                            Id = new Guid("4aef29cc-0f44-4e25-a704-902804424e41"),
                            Nombre = "CORONANGO"
                        },
                        new
                        {
                            Id = new Guid("9005ddce-0399-4cab-8496-456b816bcfeb"),
                            Nombre = "CUAUTLANCINGO"
                        },
                        new
                        {
                            Id = new Guid("54870e6a-687e-4ed5-8882-e6cc3d2f3a3c"),
                            Nombre = "CUETZALAN DEL PROGRESO"
                        },
                        new
                        {
                            Id = new Guid("51d0e71c-1ce2-4874-8eeb-57080ca1bd7b"),
                            Nombre = "ESPERANZA"
                        },
                        new
                        {
                            Id = new Guid("3910b3bd-9281-4568-bda3-942a24c94b9c"),
                            Nombre = "GUADALUPE VICTORIA"
                        },
                        new
                        {
                            Id = new Guid("2d3de914-b664-4219-9faa-675431c332b7"),
                            Nombre = "HUAUCHINANGO"
                        },
                        new
                        {
                            Id = new Guid("2603582a-751a-4fbc-8391-e6168f3afafc"),
                            Nombre = "HUEHUETLA"
                        },
                        new
                        {
                            Id = new Guid("57fc7f0d-f60d-4b2b-a9aa-eacb174d7592"),
                            Nombre = "HUEJOTZINGO"
                        },
                        new
                        {
                            Id = new Guid("c0a081c3-7bb4-49a6-80a5-c0ab374fe23b"),
                            Nombre = "HUEYTAMALCO"
                        },
                        new
                        {
                            Id = new Guid("d26d3ce6-9743-497b-a8f3-f267e49918fb"),
                            Nombre = "IZUCAR DE MATAMOROS"
                        },
                        new
                        {
                            Id = new Guid("efcddcba-b5d6-4331-b9de-5a80228c3327"),
                            Nombre = "JUAN C. BONILLA"
                        },
                        new
                        {
                            Id = new Guid("9a631574-5367-4dbe-b233-d9b4fa2d4cc3"),
                            Nombre = "LIBRES"
                        },
                        new
                        {
                            Id = new Guid("e6c3c45c-9c22-4949-a697-2861723754ea"),
                            Nombre = "LOS REYES DE JUAREZ"
                        },
                        new
                        {
                            Id = new Guid("13e0d93f-8bad-4e1a-98fd-5c9f1b28e1c1"),
                            Nombre = "METLALTOYUCA"
                        },
                        new
                        {
                            Id = new Guid("e7b9f2d3-0fdc-4659-8e39-f1afe19616a2"),
                            Nombre = "OCOYUCAN"
                        },
                        new
                        {
                            Id = new Guid("dc6cdefc-c85a-48cc-8903-c4f6667d3feb"),
                            Nombre = "ORIENTAL"
                        },
                        new
                        {
                            Id = new Guid("45d33258-4f97-4ced-99a1-467449ef159d"),
                            Nombre = "PALMAR DE BRAVO"
                        },
                        new
                        {
                            Id = new Guid("4fd1f509-0631-4439-bf51-fb8dfc615fa5"),
                            Nombre = "PIAXTLA"
                        },
                        new
                        {
                            Id = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "PUEBLA"
                        },
                        new
                        {
                            Id = new Guid("53c9635e-f7a6-45dc-a252-d1cd45d5f42c"),
                            Nombre = "SAN ANDRES CHOLULA"
                        },
                        new
                        {
                            Id = new Guid("a7dd00ae-a69c-4b94-9b44-d09029d2e493"),
                            Nombre = "SAN GABRIEL CHILAC"
                        },
                        new
                        {
                            Id = new Guid("26935263-7f17-4db2-bfb7-908cd3cbad54"),
                            Nombre = "SAN JOSE CHIAPA"
                        },
                        new
                        {
                            Id = new Guid("4ec19346-41d3-4e07-8731-6b9fdc68e976"),
                            Nombre = "SAN MARTIN TEXMELUCAN"
                        },
                        new
                        {
                            Id = new Guid("8cd95bf0-a260-4e8b-9306-126c117e76a3"),
                            Nombre = "SAN PEDRO CHOLULA"
                        },
                        new
                        {
                            Id = new Guid("22a067fb-bac4-42d9-89f4-54eaf6995a45"),
                            Nombre = "SAN SALVADOR EL SECO"
                        },
                        new
                        {
                            Id = new Guid("f6b2c9a2-a8a0-457f-a618-f4fed4403ff6"),
                            Nombre = "SANTA RITA TLAHUAPAN"
                        },
                        new
                        {
                            Id = new Guid("070dd2bb-10cf-411b-b5e5-fcaa42de9656"),
                            Nombre = "SANTIAGO MIAHUATLAN"
                        },
                        new
                        {
                            Id = new Guid("8a115e57-7789-4db1-b4cd-961cc0cb50f8"),
                            Nombre = "TECALI DE HERRERA"
                        },
                        new
                        {
                            Id = new Guid("16656bd5-ea70-46a9-adc2-acd89cc2fb63"),
                            Nombre = "TECAMACHALCO"
                        },
                        new
                        {
                            Id = new Guid("829d477c-f775-4c88-9953-85d22ba08598"),
                            Nombre = "TEHUACAN"
                        },
                        new
                        {
                            Id = new Guid("69dd05ed-5bb1-4f47-bc2c-ee48f63e2339"),
                            Nombre = "TEHUITZINGO"
                        },
                        new
                        {
                            Id = new Guid("c7fd150d-2594-4b43-baed-cbdd53be44d6"),
                            Nombre = "TEPANCO DE LOPEZ"
                        },
                        new
                        {
                            Id = new Guid("5910d6e7-8c16-4598-9630-1f59d48a71d7"),
                            Nombre = "TEPATLAXCO DE HIDALGO"
                        },
                        new
                        {
                            Id = new Guid("d5b17b0b-1b1c-4b65-983d-113ad6d561fb"),
                            Nombre = "TEPEACA"
                        },
                        new
                        {
                            Id = new Guid("b62bfed7-4c62-41e0-bfb2-10ca87db6e91"),
                            Nombre = "TEPEOJUMA"
                        },
                        new
                        {
                            Id = new Guid("d94a72c8-8670-4344-ab47-a78c2fefadef"),
                            Nombre = "TEPEXI DE RODRIGUEZ"
                        },
                        new
                        {
                            Id = new Guid("088e4526-c5b8-442b-aa82-96d5c4bb294b"),
                            Nombre = "TEPEYAHUALCO"
                        },
                        new
                        {
                            Id = new Guid("609ebfc5-4b53-46b3-95d5-00d1952f7509"),
                            Nombre = "TETELA DE OCAMPO"
                        },
                        new
                        {
                            Id = new Guid("815dd755-5c1b-440f-90eb-52c6640f873c"),
                            Nombre = "TEZIUTLAN"
                        },
                        new
                        {
                            Id = new Guid("e455c8ee-fe22-4913-a6c0-2b206e2cc8e8"),
                            Nombre = "TLACOTEPEC DE BENITO JUAREZ"
                        },
                        new
                        {
                            Id = new Guid("3a74ce88-ba94-4988-bb2b-434a9c208d28"),
                            Nombre = "TLALTENANGO"
                        },
                        new
                        {
                            Id = new Guid("71222470-32e9-4f76-ba77-6af9e2c98d57"),
                            Nombre = "TLAOLA"
                        },
                        new
                        {
                            Id = new Guid("a68b6bb8-07ea-49a9-bf68-2cec60a131ce"),
                            Nombre = "TLAPANALA"
                        },
                        new
                        {
                            Id = new Guid("34b45ec0-f95a-48aa-8fdb-cb3cd43849a7"),
                            Nombre = "TLATLAUQUITEPEC"
                        },
                        new
                        {
                            Id = new Guid("7cd8ed93-5d81-451f-80ad-314a359c9881"),
                            Nombre = "VILLA LAZARO CARDENAS"
                        },
                        new
                        {
                            Id = new Guid("8e77a494-ce8b-4500-b883-cb24e774d350"),
                            Nombre = "XICOTEPEC DE JUAREZ"
                        },
                        new
                        {
                            Id = new Guid("7ec98118-cd95-440e-ae88-3e8fbb68486b"),
                            Nombre = "ZACAPOAXTLA"
                        },
                        new
                        {
                            Id = new Guid("768aff2f-8946-45ff-ba24-d0065b01b7de"),
                            Nombre = "ZACATLAN"
                        },
                        new
                        {
                            Id = new Guid("d62af5ec-82e5-4515-8e19-04c8a10c9161"),
                            Nombre = "ZARAGOZA"
                        },
                        new
                        {
                            Id = new Guid("b6532a44-f248-4575-ba87-b6374cf2322f"),
                            Nombre = "ZOQUITLAN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
