// <auto-generated />
using System;
using DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBContext.Migrations
{
    [DbContext(typeof(ControlAsistenciaDBContext))]
    [Migration("20220830042828_update-Inmueble")]
    partial class updateInmueble
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControlAsistencia_.Models.Asistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdEmpleado")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("ControlAsistencia_.Models.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adscripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaIngreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Huella")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("IdInmueble")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroExpediente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("ControlAsistencia_.Models.Inmueble", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdMunicipio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inmueble");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea0787ab-3057-4201-b47e-69a5189a761b"),
                            Direccion = "CALLE 2 ORIENTE ENTRE CALLE 8 NORTE Y CALLE 10 ORIENTE.",
                            IdMunicipio = new Guid("0b476639-85d3-4931-9394-3d10b3b40648"),
                            Nombre = "UNIDAD DE INVESTIGACION ACAJETE"
                        },
                        new
                        {
                            Id = new Guid("54d12595-7a9e-4592-8c0b-99da2932fcd5"),
                            Direccion = "CALLE ALLENDE NO. 1 COL. CENTRO SAN JOSÉ ACATENO",
                            IdMunicipio = new Guid("883fd478-e136-4504-a096-1b8d30ab8639"),
                            Nombre = "UNIDAD DE INVESTIGACION ACATENO"
                        },
                        new
                        {
                            Id = new Guid("997a62a8-bd78-4381-a255-d9a8c3832e41"),
                            Direccion = "AV. REFORMA 22 COLONIA CENTRO ENTRE EMILIANO ZAPATA Y VENUSTIANO C",
                            IdMunicipio = new Guid("b8c23bfb-5297-4c64-b49d-6bcaa97f1d12"),
                            Nombre = "CENTRO DE JUSTICIA PARA LAS MUJERES EN ACATLAN DE OSORIO"
                        },
                        new
                        {
                            Id = new Guid("0fa248d3-69f1-4298-bb11-81e6b18a398e"),
                            Direccion = "CARRETERA INTERNACIONAL MEXICO -OAXACA KM152+200, BARRIO LA PALMA , ACATLAN DE OSORIO PUEBLA",
                            IdMunicipio = new Guid("b8c23bfb-5297-4c64-b49d-6bcaa97f1d12"),
                            Nombre = "CASA DE JUSTICIA ACATLAN DE OSORIO"
                        },
                        new
                        {
                            Id = new Guid("6f3a6d73-cab8-47dd-9d84-f7df07de7df3"),
                            Direccion = "CARRETERA FEDERAL NO.19, ACATLÁN DE OSORIO, PUEBLA",
                            IdMunicipio = new Guid("b8c23bfb-5297-4c64-b49d-6bcaa97f1d12"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS ACATLÁN DE OSORIO "
                        },
                        new
                        {
                            Id = new Guid("9da88dc2-6616-4163-930d-fe1faca21657"),
                            Direccion = "CARRETERA INTERNACIONAL, BARRIO LA PALMA ACATLAN DE OSORIO  ",
                            IdMunicipio = new Guid("b8c23bfb-5297-4c64-b49d-6bcaa97f1d12"),
                            Nombre = "SEMEFO ACATLAN DE OSORIO "
                        },
                        new
                        {
                            Id = new Guid("75b487fb-b434-49c7-abc7-77250606a1a4"),
                            Direccion = "AV. IGNACIO ROMERO VARGAS 201 COL CENTRO CP 75150",
                            IdMunicipio = new Guid("0ddfe43e-a48a-4f89-bce3-ce093d05c35f"),
                            Nombre = "UNIDAD DE INVESTIGACION ACATZINGO"
                        },
                        new
                        {
                            Id = new Guid("12ff0d33-065d-4d31-842a-91811242674b"),
                            Direccion = "CALLE HIDALGO SUR  S/N COL. CENTRO (DENTRO DE LA PRESIDENCIA MUNICIPAL ",
                            IdMunicipio = new Guid("7c58f0ba-3d86-4743-a359-75df6fdbc64f"),
                            Nombre = "UNIDAD DE INVESTIGACIÓN AHUAZOTEPEC "
                        },
                        new
                        {
                            Id = new Guid("4179b35b-018d-4fc2-847a-97aad0a386ea"),
                            Direccion = "CARRETERA ESTATAL 690 S/N , AJALPAN , PUEBLA, CP.: 75910",
                            IdMunicipio = new Guid("4b97a0d5-3da2-4a2c-97e5-eb0ed561299d"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS  AJALPAN "
                        },
                        new
                        {
                            Id = new Guid("7fea22c0-e0a7-4fc2-ad47-d081064dffdc"),
                            Direccion = "CALLE GUERRERO SIN NÚMERO, AJALPAN PUEBLA",
                            IdMunicipio = new Guid("4b97a0d5-3da2-4a2c-97e5-eb0ed561299d"),
                            Nombre = "UNIDAD DE INVESTIGACION AJALPAN"
                        },
                        new
                        {
                            Id = new Guid("8bebb72d-afc0-47a9-bfcb-bbc4135c1af2"),
                            Direccion = "CARRETERA ESTATAL TEHUACAN TEOTITLÁN OAXACA, TRAMO DE CHILACALTEPEXI,CP.: 75914",
                            IdMunicipio = new Guid("0c53a94f-3779-46b9-aa25-1bfe43c046e4"),
                            Nombre = "ARCO DE SEGURIDAD DE ALTEPEXI "
                        },
                        new
                        {
                            Id = new Guid("a2b4a20c-3c46-437a-a2ac-9c876acacc7e"),
                            Direccion = "CALLE FRANCISCO I. MADERO 109 COLONIA CENTRO BARRIO DE SANTIAGO, AMOZOC, PUE.",
                            IdMunicipio = new Guid("c95ce227-0ffa-4eae-b23e-bdd3c19bc822"),
                            Nombre = "UNIDAD DE INVESTIGACION AMOZOC"
                        },
                        new
                        {
                            Id = new Guid("8a363d39-c4da-430d-8848-42bf513866eb"),
                            Direccion = "KM 19.5 CARRETERA FEDERAL PUEBLA - TEHUACAN, COLONIA SAN JOSE LAS FLORES, CP 72980, AMOZOC",
                            IdMunicipio = new Guid("c95ce227-0ffa-4eae-b23e-bdd3c19bc822"),
                            Nombre = "ARCHIVO Y BODEGA DE INDICIOS"
                        },
                        new
                        {
                            Id = new Guid("aac51f16-f316-44ac-a2fa-473f5f82199d"),
                            Direccion = "02 ORIENTE SIN NUMERO, COLONIA CENTRO, ATEMPAN, PUEBLA",
                            IdMunicipio = new Guid("c5c10ff1-a75c-432e-b5df-96086cdfe47b"),
                            Nombre = "UNIDAD DE INVESTIGACION ATEMPAN "
                        },
                        new
                        {
                            Id = new Guid("5398b61c-1577-4c36-a68f-085460f97b08"),
                            Direccion = "CALLE 5 DE FEBRERO ESQUINA MIGUEL HIDALGO COL LA CRUZ",
                            IdMunicipio = new Guid("61203fd8-1089-478e-8061-78d51358c7ad"),
                            Nombre = "UNIDAD DE INVESTIGACION ATENCINGO"
                        },
                        new
                        {
                            Id = new Guid("76e1e97d-1ce0-4335-ac9e-981aeb1562fa"),
                            Direccion = "AUTOPISTA SIGLO XXI, KM 15+600 ATLIXCO,PUEBLA",
                            IdMunicipio = new Guid("0297d60e-31e1-4cb7-973a-a9f9104e7dc9"),
                            Nombre = "ARCO DE SEGURIDAD DE ATLÍXCO "
                        },
                        new
                        {
                            Id = new Guid("16c18dc8-dbaf-4b0c-b8df-9dd6bbb4385b"),
                            Direccion = "BOULEVARD GENERAL MORENO VALLE NO. 1604, COL. TIZAYUCA ,ATLIXCO PUE. CP.: 74200",
                            IdMunicipio = new Guid("0297d60e-31e1-4cb7-973a-a9f9104e7dc9"),
                            Nombre = "CASA DE JUSTICIA ATLIXCO "
                        },
                        new
                        {
                            Id = new Guid("f6f5ec29-7b21-462a-90b7-7c6b6d617a59"),
                            Direccion = "REVOLUCIÓN NO. 6202, COL. EL LEÓN ATLIXCO PUE, CP.: 74360",
                            IdMunicipio = new Guid("0297d60e-31e1-4cb7-973a-a9f9104e7dc9"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS  ATLIXCO "
                        },
                        new
                        {
                            Id = new Guid("efe8487c-1068-4e19-aad1-6c0f2c4d168c"),
                            Direccion = "CALLE 5 PONIENTE 113, COL. CENTRO ATLIXCO ",
                            IdMunicipio = new Guid("0297d60e-31e1-4cb7-973a-a9f9104e7dc9"),
                            Nombre = "SEMEFO ATLIXCO"
                        },
                        new
                        {
                            Id = new Guid("e484e377-cc09-4098-b595-2966661b1cac"),
                            Direccion = "CALLE CONSTITUCION S/N ENTRE 16 DE SEPTIEMBRE Y DOMINGO ARENAS, PRESIDENCIA MUNICIPAL CALPAN, PUE.",
                            IdMunicipio = new Guid("974ec286-e9d0-4ddd-9adb-60e0364c8a9c"),
                            Nombre = "UNIDAD DE INVESTIGACION CALPAN"
                        },
                        new
                        {
                            Id = new Guid("df565b02-4f00-4d24-9c6b-c935edc2b0bb"),
                            Direccion = "KM.28+285 CARRETERA FEDERAL EL SECO ASUMBULLA, CD. SERDAN, PUEBLA CP.: 75520",
                            IdMunicipio = new Guid("f751758f-84ad-43ad-a5d5-b51400ffa92c"),
                            Nombre = "CASA DE JUSTICIA CHALCHICOMULA DE SESMA "
                        },
                        new
                        {
                            Id = new Guid("5862a80d-c5ec-4389-867b-ec4bc60e9abc"),
                            Direccion = "CARRETERA FEDERAL SERDÁN EL SECO KILOMETRO 28, CD. SERDAN PUEBLA CP.: 75520",
                            IdMunicipio = new Guid("f751758f-84ad-43ad-a5d5-b51400ffa92c"),
                            Nombre = "CENTRO INTEGRAL DE SERVICIOS  CHALCHICOMULA DE SESMA "
                        },
                        new
                        {
                            Id = new Guid("f350b9c0-947e-4428-a96f-589563bd3d5f"),
                            Direccion = "CALLE 5 PONIENTE SIN NUMERO, C.D. SERDAN, CHALCHICOMULA DE SESMA ",
                            IdMunicipio = new Guid("f751758f-84ad-43ad-a5d5-b51400ffa92c"),
                            Nombre = "SEMEFO CIUDAD SERDAN "
                        },
                        new
                        {
                            Id = new Guid("73132bd8-3ce8-4b7a-a6c8-beed00da244a"),
                            Direccion = "CERRO EL PAPAGAYO",
                            IdMunicipio = new Guid("a4662e9d-4c5b-4fa3-803c-6ab3e0e0b7cc"),
                            Nombre = "ANTENA TETELES , EL PAPAYO Y REPETIDOR SAN BERNARDINA CHALCHIHUAPAN "
                        },
                        new
                        {
                            Id = new Guid("bcfb55fe-413a-4c8d-8990-f6bd1594db5d"),
                            Direccion = "CALLE REFORMA Y 5 NORTE COLONIA CENTRO, CHIAUTLA DE TAPIA",
                            IdMunicipio = new Guid("76a59c1c-6538-4a5b-9d55-4ed081309a70"),
                            Nombre = "UNIDAD DE INVESTIGACION CHIAUTLA DE TAPIA"
                        },
                        new
                        {
                            Id = new Guid("f04b392b-601f-4c73-b60e-6b95c37b4176"),
                            Direccion = "CALLE RAYON NUMERO 4 COL. CENTRO",
                            IdMunicipio = new Guid("6dc36e6e-8182-4a61-8c1a-83d03d36a673"),
                            Nombre = "UNIDAD DE INVESTIGACION CHIETLA"
                        },
                        new
                        {
                            Id = new Guid("7d977d82-0622-4415-adfa-168f4a78dffd"),
                            Direccion = "BOULEVARD EMILIANO ZAPATA SIN NUMERO, INTERIOR DEL PANTEON MUNICIPAL, CHIGNAHUAPAN,PUEBLA ",
                            IdMunicipio = new Guid("796fe037-7c39-48a1-be38-3d883e228409"),
                            Nombre = "SEMEFO CHIGNAHUAPAN"
                        },
                        new
                        {
                            Id = new Guid("f47edbb8-650f-4756-a5f3-fbf4d62c1261"),
                            Direccion = "LIBRAMIENTOCHIGNAHUAPAN - ZACATLAN, KM 4.5 BARRIO TOLTEMPAN, CHIGNAHUAPAN, PUE.",
                            IdMunicipio = new Guid("796fe037-7c39-48a1-be38-3d883e228409"),
                            Nombre = "UNIDAD DE INVESTIGACION CHIGNAHUAPAN"
                        },
                        new
                        {
                            Id = new Guid("47c5a6a5-ebca-460c-a931-b446bc4ae13a"),
                            Direccion = "AV. 5 DE FEBRERO NORTE SIN NUMERO COL. EL MONTERO CORONANGO, PUEBLA  COMPLEJO METROPOLITANO",
                            IdMunicipio = new Guid("4aef29cc-0f44-4e25-a704-902804424e41"),
                            Nombre = "UNIDAD DE INVESTIGACION  CORONANGO"
                        },
                        new
                        {
                            Id = new Guid("0dbd6fd2-8c56-4562-8e21-dd018b174ee1"),
                            Direccion = "PERIFERICO ECOLÓGICO KILÓMETRO 3.5 ANTIGUO CAMINO A SAN FRANCISCO OCOTLÁN,CUAUTLANCINGO PUEBLA",
                            IdMunicipio = new Guid("9005ddce-0399-4cab-8496-456b816bcfeb"),
                            Nombre = "COMPLEJO METROPOLITANO SEGURIDAD PÚBLICA  (C5) "
                        },
                        new
                        {
                            Id = new Guid("66451a35-3553-401e-a2c3-d02d5d80a805"),
                            Direccion = "CALLE CAMINO NACIONAL ESQUINA CON AQUILES SERDAN SIN NUMERO, COLONIA BELLO HORIZONTE, CUAUTLANCINGO  COMPLEJO DE SEGURIDAD",
                            IdMunicipio = new Guid("9005ddce-0399-4cab-8496-456b816bcfeb"),
                            Nombre = "UNIDAD DE INVESTIGACION CUAUTLANCINGO"
                        },
                        new
                        {
                            Id = new Guid("02794a34-a930-4f9b-bfed-0294a49b7288"),
                            Direccion = "CALLE AQUILES SERDAN ESQUINA CON 20 DE NOVIEMBRE SIN NUMERO, COLONIA BELLO HORIZONTE, CUAUTLANCINGO",
                            IdMunicipio = new Guid("9005ddce-0399-4cab-8496-456b816bcfeb"),
                            Nombre = "CENTRO INTEGRAL DE SERVICIOS CUAUTLANCINGO"
                        },
                        new
                        {
                            Id = new Guid("a997fc37-85dd-4508-9a5e-76f1a64d8ccc"),
                            Direccion = "AV. SAN LORENZO ALMECATLA SIN NUMERO PLAZA MOVAR SANCTORUM",
                            IdMunicipio = new Guid("9005ddce-0399-4cab-8496-456b816bcfeb"),
                            Nombre = " UNIDAD DE INVESTIGACIÓN VW"
                        },
                        new
                        {
                            Id = new Guid("8c0c4bc9-bbad-44d6-8fde-76be64c12cb8"),
                            Direccion = "CARRETERA A TLAXCALA KM 10 CUAUTLANCINGO, PUEBLA",
                            IdMunicipio = new Guid("9005ddce-0399-4cab-8496-456b816bcfeb"),
                            Nombre = "DEPOSITO DE VEHICULOS CUAUTLANCINGO (CAPULIN)"
                        },
                        new
                        {
                            Id = new Guid("c79300f4-0dfc-46da-ba2b-63c882bc80cb"),
                            Direccion = "CALLE MIGUEL ALVARADO ESQUINA CON ABASOLO S/N COLONIA CENTRO C.P. 75040 CUETZALAN PUEBLA",
                            IdMunicipio = new Guid("54870e6a-687e-4ed5-8882-e6cc3d2f3a3c"),
                            Nombre = "UNIDAD DE INVESTIGACION CUETZALÁN DEL PROGRESO "
                        },
                        new
                        {
                            Id = new Guid("d2aba852-a956-4625-8b91-46594f19e8ae"),
                            Direccion = "CALLE 12 NORTE SEGUNDA SECCION 22, ESPERANZA, PUE.",
                            IdMunicipio = new Guid("51d0e71c-1ce2-4874-8eeb-57080ca1bd7b"),
                            Nombre = "UNIDAD DE INVESTIGACION ESPERANZA"
                        },
                        new
                        {
                            Id = new Guid("db79d375-08c0-402c-9891-a1e1ea6e47b4"),
                            Direccion = "AV. 5 DE MAYO NO.1 EXTERIOR DE LA PRESIDENCIA MUNICIPAL, GUADALUPE VICTORIA , PUEBLA",
                            IdMunicipio = new Guid("3910b3bd-9281-4568-bda3-942a24c94b9c"),
                            Nombre = "UNIDAD DE INVESTIGACION Y MEDIOS ALTERNATIVOS"
                        },
                        new
                        {
                            Id = new Guid("21ece737-52f7-4b09-bcae-69005426a9cd"),
                            Direccion = "CAMINO A CATALINA S/N COLONIA EL POTRO, HUAUCHINANGO, PUEBLA CP.: 73176",
                            IdMunicipio = new Guid("2d3de914-b664-4219-9faa-675431c332b7"),
                            Nombre = "CASA DE JUSTICIA HUAUCHINANGO "
                        },
                        new
                        {
                            Id = new Guid("34171fa2-4d08-47d9-907b-d8e9f74ea9a9"),
                            Direccion = "CALLE TIRZO TELLEZ SIN NUMERO COL. EL CRISTO, HUAUCCHINANGO, PUEBLA ",
                            IdMunicipio = new Guid("2d3de914-b664-4219-9faa-675431c332b7"),
                            Nombre = "SEMEFO HUAUCHINANGO"
                        },
                        new
                        {
                            Id = new Guid("dd381283-4c21-484b-91e2-305c7803c22d"),
                            Direccion = "CALLE JUAREZ SUR S/N COL. YALU LOCALUDAD PUTAX-EAT, HUEHUETLA, PUE.",
                            IdMunicipio = new Guid("2603582a-751a-4fbc-8391-e6168f3afafc"),
                            Nombre = "UNIDAD DE INVESTIGACION HUEHUETLA "
                        },
                        new
                        {
                            Id = new Guid("418b2be0-cd91-4bad-b9f4-c6f65dc2119d"),
                            Direccion = "JUNTA AUXULIAR SANTA ANA XALMIMILULCO, ANTIGUA FINCA DE SANTA ANA DE ABAJO PREDIO 5",
                            IdMunicipio = new Guid("57fc7f0d-f60d-4b2b-a9aa-eacb174d7592"),
                            Nombre = "SEMEFO HUEJOTZINGO TERRENO"
                        },
                        new
                        {
                            Id = new Guid("ab889720-0f37-4d94-a903-741bfc3ff9fb"),
                            Direccion = "CARRETERA MÉXICO -PUEBLA KM100+200 HUEJOTZINGO ,PUEBLA",
                            IdMunicipio = new Guid("57fc7f0d-f60d-4b2b-a9aa-eacb174d7592"),
                            Nombre = "ARCO DE SEGURIDAD HUEJOTZINGO "
                        },
                        new
                        {
                            Id = new Guid("1c8e7a04-f572-402e-af53-175d13989394"),
                            Direccion = "AV DE LAS HUERTAS 917 CUARTO BARRIO COL. CENTRO, HUEJOTZINGO, PUEBLA, CP.: 74168",
                            IdMunicipio = new Guid("57fc7f0d-f60d-4b2b-a9aa-eacb174d7592"),
                            Nombre = "UNIDAD DE INVESTIGACION  ADSCRITA A JUZGADOS PENALES Y CIVILES "
                        },
                        new
                        {
                            Id = new Guid("8eeef5ac-4c1e-4a29-b573-3a43771ff75d"),
                            Direccion = "BLVD. 18 DE MARZO NUMERO 52 COLONIA EL PARAISO, HUEJOTZINGO, PUE.",
                            IdMunicipio = new Guid("57fc7f0d-f60d-4b2b-a9aa-eacb174d7592"),
                            Nombre = "AGENCIA ESTATAL DE INVESTIGACIÓN"
                        },
                        new
                        {
                            Id = new Guid("49c6c10e-90c6-43fd-86f2-bd7365a08f57"),
                            Direccion = "CALLE INDEPENDENCIA ESQ. CON CALLE 5 DE MAYO S/N COL. CENTRO, HUEYTAMALCO, PUE",
                            IdMunicipio = new Guid("c0a081c3-7bb4-49a6-80a5-c0ab374fe23b"),
                            Nombre = "UNIDAD DE INVESTIGACION HUEYTAMALCO "
                        },
                        new
                        {
                            Id = new Guid("5c6b1182-7c0e-4567-9cdf-0a2d20b09fe5"),
                            Direccion = "PRIVADA UNIVERSIDAD II SAN MARTIN ALCHICHICA, IZUCAR DE MATAMOROS,PUEBLA ",
                            IdMunicipio = new Guid("d26d3ce6-9743-497b-a8f3-f267e49918fb"),
                            Nombre = "UNIDAD DE INVESTIGACION CRIMINAL Y UNIDAD DE ATENCIÓN TEMPRANA  IZUCAR DE MATAMOROS "
                        },
                        new
                        {
                            Id = new Guid("18af5009-c71b-4ef5-aba2-0e47881a77ca"),
                            Direccion = "CARRETERA FEDERAL IZÚCAR DE MATAMOROS KM61+800 IZUCAR DE MATAMOROS",
                            IdMunicipio = new Guid("d26d3ce6-9743-497b-a8f3-f267e49918fb"),
                            Nombre = "ARCO DE SEGURIDAD DE IZÚCAR DE MATAMOROS "
                        },
                        new
                        {
                            Id = new Guid("a4620e16-43bb-4478-a846-8b14f2a87d9a"),
                            Direccion = "CARRETERA FEDERAL PUEBLA-IZUCAR DE MATAMOROS NO. 2119, COL. GALARZA, IZUCAR DE MATAMOROS, PUEBLA",
                            IdMunicipio = new Guid("d26d3ce6-9743-497b-a8f3-f267e49918fb"),
                            Nombre = "CASA DE JUSTICIA IZÚCAR DE MATAMOROS"
                        },
                        new
                        {
                            Id = new Guid("dfaeed5a-c80f-4191-9fcf-01d4b4a753db"),
                            Direccion = "INTERNACIONAL A OAXACA 2,BARRIO DE SAN JUAN PIAXTLA IZUCAR DE MATAMOROS ,PUE",
                            IdMunicipio = new Guid("d26d3ce6-9743-497b-a8f3-f267e49918fb"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS  IZUCAR DE MATAMOROS "
                        },
                        new
                        {
                            Id = new Guid("379b9188-cb1e-46e7-a4c7-3faa87163b45"),
                            Direccion = "  PANTEON MUNICIPAL, BARRIO DE SANTA CRUZ, TEXCOCO, CALLE REVOLUCION Y HERCULANO SANCHEZ ",
                            IdMunicipio = new Guid("d26d3ce6-9743-497b-a8f3-f267e49918fb"),
                            Nombre = "SEMEFO IZUCAR DE MATAMOROS "
                        },
                        new
                        {
                            Id = new Guid("9e54398a-156c-4d59-a439-8dc24d54e427"),
                            Direccion = "CALLE 5 DE MAYO S/N COLONIA CENTRO, JUAN C. BONILLA, PUE.",
                            IdMunicipio = new Guid("efcddcba-b5d6-4331-b9de-5a80228c3327"),
                            Nombre = "UNIDAD DE INVESTIGACION JUAN C BONILLA"
                        },
                        new
                        {
                            Id = new Guid("633519e6-ead6-4b81-8034-cc407301a215"),
                            Direccion = "CALLE LERDO NUMERO 988, LIBRES, PUEBLA",
                            IdMunicipio = new Guid("9a631574-5367-4dbe-b233-d9b4fa2d4cc3"),
                            Nombre = "UNIDAD DE INVESTIGACION LIBRES"
                        },
                        new
                        {
                            Id = new Guid("ae00d1a5-1d40-41d2-8a08-5755abddbdbf"),
                            Direccion = "CALLE 4 ORIENTE SIN NUMERO BARRIO DE GUADALUPE ",
                            IdMunicipio = new Guid("9a631574-5367-4dbe-b233-d9b4fa2d4cc3"),
                            Nombre = "SEMEFO LIBRES"
                        },
                        new
                        {
                            Id = new Guid("0a0322cb-1b9c-4702-9df4-9fdf87b39bf0"),
                            Direccion = "CALLE LERDO NUMERO 988, LOS CONOS LIBRES, PUEBLA",
                            IdMunicipio = new Guid("9a631574-5367-4dbe-b233-d9b4fa2d4cc3"),
                            Nombre = "CASA DE JUSTICIA LIBRES"
                        },
                        new
                        {
                            Id = new Guid("88754927-6c86-414a-b1a7-1d9a50a45d54"),
                            Direccion = "AVENIDA MERINO FERNANDEZ ENTRE CALLE JUAREZ Y CALLE AYUNTAMIENTO, PRESIDENCIA MUNCIAL, COL. CENTRO, LOS REYES DE JUAREZ, PUE.",
                            IdMunicipio = new Guid("e6c3c45c-9c22-4949-a697-2861723754ea"),
                            Nombre = "UNIDAD DE INVESTIGACION LOS REYES DE JUAREZ"
                        },
                        new
                        {
                            Id = new Guid("5fabc11c-cb4e-4120-805d-4334f47d233c"),
                            Direccion = "AVENIDA REYES GARCIA 57 COLONIA ERMITA, METLALTOYUCA, PUEBLA. CP 73000",
                            IdMunicipio = new Guid("13e0d93f-8bad-4e1a-98fd-5c9f1b28e1c1"),
                            Nombre = "UNIDAD DE INVESTIGACION METLATOYUCA "
                        },
                        new
                        {
                            Id = new Guid("6d1c2e9c-5fe4-45ba-9da7-29f76bac1841"),
                            Direccion = "PLAZA PRINCIPAL S/N PLANTA BAJA, PALACIO MUNICIPAL, COL. CENTRO, SANTA CLARA OCOYUCAN",
                            IdMunicipio = new Guid("e7b9f2d3-0fdc-4659-8e39-f1afe19616a2"),
                            Nombre = "UNIDAD DE INVESTIGACION OCOYUCAN"
                        },
                        new
                        {
                            Id = new Guid("9f24386a-81ef-4601-bc4f-2b0ee4b96639"),
                            Direccion = "CAMINO AL PANTEON SIN NUMERO COLONIA CENTRO, ORIENTAL, PUE.",
                            IdMunicipio = new Guid("dc6cdefc-c85a-48cc-8903-c4f6667d3feb"),
                            Nombre = "SEMEFO ORIENTAL"
                        },
                        new
                        {
                            Id = new Guid("604009aa-027e-490a-b552-9c76101b6d8a"),
                            Direccion = "AV. AYUNTAMIENTO NO. 3 COL. CENTRO CP 75020",
                            IdMunicipio = new Guid("dc6cdefc-c85a-48cc-8903-c4f6667d3feb"),
                            Nombre = "UNIDAD DE INVESTIGACION ORIENTAL"
                        },
                        new
                        {
                            Id = new Guid("97312b95-bae0-4624-a208-a8f73533c216"),
                            Direccion = "CARRETERA MÉXICO VERACRUZ KM 166+500PALMAR DE BRAVO , PUEBLA",
                            IdMunicipio = new Guid("45d33258-4f97-4ced-99a1-467449ef159d"),
                            Nombre = "ARCO DE SEGURIDAD PALMAR DE BRAVO "
                        },
                        new
                        {
                            Id = new Guid("aab687d1-1489-46b4-91ef-5a04e387d9ef"),
                            Direccion = "CALLE NICOLAS BRAVO #504 COL. CENTRO PLAMAR DE BRAVO ",
                            IdMunicipio = new Guid("45d33258-4f97-4ced-99a1-467449ef159d"),
                            Nombre = "UNIDAD DE INVESTIGACION PALMAR DE BRAVO "
                        },
                        new
                        {
                            Id = new Guid("c3a22f92-ab1f-4078-9bf9-c8e0e05f1345"),
                            Direccion = "PLAZA EXPLANADA PALACIO MUNICIPAL S/N COL. CENTRO PRIMER PISO",
                            IdMunicipio = new Guid("4fd1f509-0631-4439-bf51-fb8dfc615fa5"),
                            Nombre = "UNIDAD DE INVESTIGACION PIAXTLA"
                        },
                        new
                        {
                            Id = new Guid("f70ae993-4797-4608-95dc-b931e68f5ccc"),
                            Direccion = "BOULEVARD HEROES 5 DE MAYO ESQUINA CON 31 ORIENTE COL.LADRILLERA DE BENITEZ CP.: 72530",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "EDIFICIO CENTRAL 04"
                        },
                        new
                        {
                            Id = new Guid("f6ea5fc3-c586-47ea-957d-9320b9464dd5"),
                            Direccion = "CALLE 17 PONIENTE NO.1919, BARRIO DE SANTIAGO,PUEBLA, PUE. CP.: 72410",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "CENTRO DE JUSTICIA PARA LAS MUJERES PUEBLA "
                        },
                        new
                        {
                            Id = new Guid("1cb1ac85-d878-42db-9ef8-ec848407ebdf"),
                            Direccion = "CALLE 10 ORIENTE NO.414,COL CENTRO PUEBLA,PUE. CP.: 72530",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "FISCALÍA ESPECIALIZADA EN INVESTIGACIÓN DE DELITOS DE VIOLENCIA DE GÉNERO CONTRA LAS MUJERES (CPJ)"
                        },
                        new
                        {
                            Id = new Guid("05f794c3-f900-4941-a15e-cca8664ac6e1"),
                            Direccion = "PRIV. 5 B SUR NO. 3706, COL. GABRIEL PASTOR, PUEBLA, PUE CP. 72420",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "INDIGENAS PERIODISTAS LGBTTQ"
                        },
                        new
                        {
                            Id = new Guid("50ff685d-2657-4042-8319-c3c6d7fa505e"),
                            Direccion = "CALLE 12 ORIENTE NO. 415 COL. CENTRO, PUEBLA, PUE.",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "FISCALIA DE DERECHOS HUMANOS"
                        },
                        new
                        {
                            Id = new Guid("3d261dbb-2a81-491a-af78-659331b86c4a"),
                            Direccion = "CALLE 6 NORTE NO.1003, COL. CENTRO,PUEBLA PUE. CP.: 72000",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "FISCALÍA ESPECIALIZADA EN INVESTIGACIÓN DE DELITOS DE VIOLENCIA DE GÉNERO CONTRA LAS MUJERES (BOCHAS)"
                        },
                        new
                        {
                            Id = new Guid("e11c2009-ce5f-4adb-aa33-c882aeff8449"),
                            Direccion = "CALLE 127 PONIENTE Y CALLE 11 SUR , COL.EX-HACIENDA CASTILLOTLA, PUEBLA,PUE",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "FISCALIA ESPECIALIZADA EN INVESTIGACION DE DELITOS DE ALTA INCIDENCIA"
                        },
                        new
                        {
                            Id = new Guid("75f66bef-947b-4731-a7c8-e6897cd0d31c"),
                            Direccion = "AV. MIGUEL HIDALGO NO. 16,COL. EL PORVENIR ,PUEBLA,PUE",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "INMUEBLE DE LA 16 ORIENTE "
                        },
                        new
                        {
                            Id = new Guid("5c49c4fa-1770-4c96-adbb-c95540a0c85d"),
                            Direccion = "DIAGONAL CUAUHTÉMOC NO.3101 COL. VALLE DORADO PUEBLA,PUE. CP.: 72070",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "INSTITUTO DE FORMACIÓN PROFESIONAL   "
                        },
                        new
                        {
                            Id = new Guid("7c90783c-73d4-4435-97f0-1255181a81ac"),
                            Direccion = "DIAGONAL DEFENSORES DE LA REPÚBLICA ESQ.10 PONIENTE COL.AMOR PUEBLA,PUE. CP.: 72140",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "COORDINACIÓN GENERAL DE MECANISMOS ALTERNATIVOS DE SOLUCION DE CONTROVERSIAS EN MATERIA PENAL"
                        },
                        new
                        {
                            Id = new Guid("5e3c77e9-74e5-4a6e-ad3d-de540745e37f"),
                            Direccion = "12 NORTE. NO.1806,COL. BARRIO DEL ALTO , PUEBLA PUE. CP.: 72146",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "FISCALIA DE ASUNTOS INTERNOS, ORGANO INTERNO DE CONTROL Y VISITADURIA "
                        },
                        new
                        {
                            Id = new Guid("f586dc78-1395-493e-87f7-16d41d377301"),
                            Direccion = "EMILIANO ZAPATA KM2.5,COL LOMAS DE SAN MIGUEL,PUEBLA,PUE. CP.: 72573",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD DE IDENTIFICACIÓN VEHICULAR "
                        },
                        new
                        {
                            Id = new Guid("9e238566-245c-44ba-a61c-8a4f7bb7f7d8"),
                            Direccion = "CAMINO AL BATÁN KM2.5 COL.LOMAS DE SAN MIGUEL PUEBLA,PUE. CP.: 72573",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD ESPECIALIZADA DE INVESTIGACIÓN DE ROBO DE VEHICULOS (OCRA)"
                        },
                        new
                        {
                            Id = new Guid("c1ee4f7d-93dd-4d48-be9d-1324a40e4fc2"),
                            Direccion = "CAMINO AL BATÁN COL.LOMAS DE SAN MIGUEL PUEBLA,PUE",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "DEPOSITO DE VEHÍCULOS OCRA - SAN MIGUEL 2"
                        },
                        new
                        {
                            Id = new Guid("7a465d4d-7292-4a37-a4fb-0d1a554573e5"),
                            Direccion = "AV. REFORMA 1305 COL CENTRO C.P. 72000",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "CENTRO INTEGRAL DE SERVICIOS  SAN JAVIER "
                        },
                        new
                        {
                            Id = new Guid("9ea85a40-40a0-441c-9cc4-0c37d28aea28"),
                            Direccion = "VÍA ATLIXCAYOTL NO. 1101, EDIFICIO SUR PLANTA BAJA , CONCEPCION LAS LAJAS , PUEBLA,PUE",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "CENTRO INTEGRAL DE SERVICIOS ANGELÓPOLIS "
                        },
                        new
                        {
                            Id = new Guid("35f7fae6-21b0-438c-966b-17442bacdf89"),
                            Direccion = "KM 2.5 CARRETERA AL BATAN , EDIFICIO ADJUNTO AL CERESO DE SAN MIGUEL PUEBLA,PUE",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "EJECUCION DE SENTENCIAS "
                        },
                        new
                        {
                            Id = new Guid("58f8f4bf-66c5-48da-a474-d360097bcb73"),
                            Direccion = "AV.105 PONIENTE ENTRE CALLE PUEBLA Y OAXACA COL.POPULAR CASTILLOTLA, PUEBLA,",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD DE INVESTIGACION LA POPULAR"
                        },
                        new
                        {
                            Id = new Guid("360e0d81-dff5-4de9-b354-1e4da4f14165"),
                            Direccion = "PROLONGACIÓN 16 ORIENTE ESQ. CON LIBRAMIENTO A TEHUACAN COL. MEXICO 68",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD DE INVESTIGACION ORIENTE"
                        },
                        new
                        {
                            Id = new Guid("e8923eed-5915-4543-9ce6-dbdfbc31c67a"),
                            Direccion = "CALLE 21 ORIENTE NO.404, COL. EL CARMEN, PUEBLA,PUE",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD DE INVESTIGACION VIRTUAL PREDENUNCIA EL CARMEN "
                        },
                        new
                        {
                            Id = new Guid("6d545b8c-a620-4871-86ef-528430c61e1e"),
                            Direccion = "9 ORIENTE NO.1405COL.CENTRO PUEBLA PUE",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD DE INVESTIGACIÓN CENTRO"
                        },
                        new
                        {
                            Id = new Guid("a63b7be7-32d5-4958-8254-1162c906ddd7"),
                            Direccion = "BOULEVARD VALSEQUILLO ESQU. 20 DE NOVIEMBRE COL. SAN BALTAZAR CAMPECHE, PUEBLA,PUE",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD DE INVESTIGACIÓN VALSEQUILLO"
                        },
                        new
                        {
                            Id = new Guid("f470ce98-458d-4a21-856d-846424d5aefc"),
                            Direccion = "CALLE 12 ORIENTE NO. 608 COL. CENTRO ,PUEBLA, PUE",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD ESPECIALIZADA ADSRCITA A LA FISCALIA METROPOLITANA (JUZGADOS PENALES)   "
                        },
                        new
                        {
                            Id = new Guid("43329601-aaf1-4505-a114-c5e2c0404ca6"),
                            Direccion = "AV. REFORMA 2704 5° PISO COL. AMOR",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "INMUEBLE CANACINTRA"
                        },
                        new
                        {
                            Id = new Guid("2d8aa1ef-75b9-4ca5-9d34-ff910f146677"),
                            Direccion = "CALLE AL ESTADIO ZARAGOZA, BARRIO DE XANENETLA, PLANTA BAJA Y PRIMER NIVEL, ESTADIO ZARAGOZA, 72000, PUEBLA, PUE.",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "ESTADIO ZARAGOZA"
                        },
                        new
                        {
                            Id = new Guid("42ae640d-789f-4262-bc0f-9fdc6ef3c504"),
                            Direccion = "13 SUR 1910 BARRIO DE SANTIAGO PUEBLA PUE",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "JUSTICIA CIUDADANA"
                        },
                        new
                        {
                            Id = new Guid("4accb2ff-b226-47ac-bfad-9055220fc68b"),
                            Direccion = "CALLE FRANCISCO I. MADERO NO. 07 COL. CENTRO, SAN PABLO XOCHIMEHUACAN",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD DE INVESTIGACIÓN VILLA FRONTERA"
                        },
                        new
                        {
                            Id = new Guid("542c1a9a-46db-451a-a395-e7ef22925811"),
                            Direccion = "RIO ATOYAC # 19 SANCTORUM",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "DEPOSITO DE VEHICULOS SANCTORUM (FINSA)"
                        },
                        new
                        {
                            Id = new Guid("79302577-eff3-4087-93db-599dc70f3c13"),
                            Direccion = "CAMINO AL BATAN NO. 12 COL. VILLA SATELITE LA CALERA PUEBLA",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = " UNIDAD DE INVESTIGACIÓN LA MARGARITA"
                        },
                        new
                        {
                            Id = new Guid("a70575f3-3ffb-4d12-af9c-8dc3b641fcbd"),
                            Direccion = "CALLE ORQUIDEAS NO. 6141 COLONIA BUGAMBILIAS CP 72580",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "ALMACEN GENERAL"
                        },
                        new
                        {
                            Id = new Guid("b06290e8-8fcc-430e-abec-1399c33c520c"),
                            Direccion = "PROLONGACION DE LA 14 SUR NUMERO 11517 COL. SAN JOSE CHAPULCO",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD DE INVESTIGACION CHAPULCO"
                        },
                        new
                        {
                            Id = new Guid("2105684c-46b6-41c5-bd73-024885f82f3e"),
                            Direccion = "PROLONGACION 11 SUR 11906, COL. GUADALUPE HIDQLGO",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "SEMEFO 11 SUR "
                        },
                        new
                        {
                            Id = new Guid("02063a14-db5e-4cb5-a163-f4e3ecbf84b3"),
                            Direccion = "CALLE 8 ORIENTE, NUMERO 1007, COLONIA SAN FRANCISCO, PUEBLA, PUE. ",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "UNIDAD INTEGRAL DE SERVICIOS EL ALTO "
                        },
                        new
                        {
                            Id = new Guid("3e885b08-c87a-457a-9b57-6939a4034323"),
                            Direccion = "AV. 25 ORIENTE  #1610 BELLA VISTA, PUEBLA, PUE.",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "AGENCIA ESTATAL DE INVESTIGACION "
                        },
                        new
                        {
                            Id = new Guid("a1a9e843-9a4e-49eb-b6be-d70511e89a75"),
                            Direccion = "AVENIDA 16 DE SEPTIEMBRE NUMERO 2904 COLONIA EL CARMEN, PUEBLA, PUE.",
                            IdMunicipio = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "FISCALIA ESPECIALIZADA DE COMBATE A LA CORRUPCION, FISCALIA ESPECIALIZADA EN INVESTIGACION DE LOS DELITOS DE DESAPARICION FORZADA DE PERSONAS Y DESAPARICION COMETIDA POR PARTICUALRES"
                        },
                        new
                        {
                            Id = new Guid("af99061f-36ab-46f4-97f5-618dad2a5cae"),
                            Direccion = "3ER RETORNO OSA MENOR NO.3, RESERVA TERRITORIAL ATLIXCAYOTL ,SAN ANDRÉS",
                            IdMunicipio = new Guid("53c9635e-f7a6-45dc-a252-d1cd45d5f42c"),
                            Nombre = "FISCALÍA ESPECIALIZADA EN INVESTIGACIÓN DE SECUESTRO Y EXTORSIÓN"
                        },
                        new
                        {
                            Id = new Guid("1c2468eb-8298-4bb5-a775-951ec6779458"),
                            Direccion = "TERCER RETORNO OSA MAYOR NO. 3, RESERVA TERRITORIAL ATLIXCAYOTL SAN ANDRES",
                            IdMunicipio = new Guid("53c9635e-f7a6-45dc-a252-d1cd45d5f42c"),
                            Nombre = "COORDINACION GENERAL DE ANALISIS DE INFORMACION "
                        },
                        new
                        {
                            Id = new Guid("2071ce79-2ad0-4f8c-b7ce-c979aeb07829"),
                            Direccion = "CARRETERA IZUCAR DE MATAMOROS S/N COL. TLAXCALANCINGO, CP.: 72820",
                            IdMunicipio = new Guid("53c9635e-f7a6-45dc-a252-d1cd45d5f42c"),
                            Nombre = "CASA DE JUSTICIA PARA ADOLESCENTES"
                        },
                        new
                        {
                            Id = new Guid("d1e510c1-98dd-49b6-a4a9-4d15658d5e12"),
                            Direccion = "PERIFÉRICO ECOLÓGICO 100 SAN BERNARDINO TLAXCALANCINGO SAN ANDRES CHOLULA",
                            IdMunicipio = new Guid("53c9635e-f7a6-45dc-a252-d1cd45d5f42c"),
                            Nombre = "CASA DE JUSTICIA SAN ANDRES CHOLULA "
                        },
                        new
                        {
                            Id = new Guid("ebcbb7fe-22b1-4fdc-8ab9-e1743671cf55"),
                            Direccion = "ANILLO PERIFERICO ECOLOGICO SIN NUEMERO COL. EMILIANO ZAPATA",
                            IdMunicipio = new Guid("53c9635e-f7a6-45dc-a252-d1cd45d5f42c"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS  SAN ANDRES CHOLULA "
                        },
                        new
                        {
                            Id = new Guid("3010e2c0-ae15-4d01-af42-eb075c067a59"),
                            Direccion = "CAMINO A CUAYANTLA NO. 1611, SAN BERNARDINO TLAXCALANCINGO, PUEBLA",
                            IdMunicipio = new Guid("53c9635e-f7a6-45dc-a252-d1cd45d5f42c"),
                            Nombre = "COMPLEJO DE SEGURIDAD PÚBLICA SAN ANDRES CHOLULA "
                        },
                        new
                        {
                            Id = new Guid("ea76efef-50bb-4c85-aa43-a834a5db3f7f"),
                            Direccion = "PERIFERICO ECOLOGÍCO ARCO SUR NO. 4000, RESERVA TERRITORIAL ATLIXCAYOTL, SAN",
                            IdMunicipio = new Guid("53c9635e-f7a6-45dc-a252-d1cd45d5f42c"),
                            Nombre = "UNIDAD DE INVESTIGACION CIUDAD JUDICIAL "
                        },
                        new
                        {
                            Id = new Guid("e1a8b510-6500-4a29-a904-de39e59c7062"),
                            Direccion = "AVENIDA NIÑOS HEROES SIN NUMERO COLONIA EL SOL, SAN GABRIEL CHILAC, PUEBLA",
                            IdMunicipio = new Guid("a7dd00ae-a69c-4b94-9b44-d09029d2e493"),
                            Nombre = "UNIDAD DE INVESTIGACION SAN GABRIEL CHILAC"
                        },
                        new
                        {
                            Id = new Guid("db4c1ada-9e03-4fd4-9887-cb1446d279c0"),
                            Direccion = "MANZANA NÚMERO 5 CIUDAD MODELO",
                            IdMunicipio = new Guid("26935263-7f17-4db2-bfb7-908cd3cbad54"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS  SAN JOSE CHIAPA "
                        },
                        new
                        {
                            Id = new Guid("7cd298aa-a271-438a-928d-3cca6e936391"),
                            Direccion = "AUTOPISTA MÉXICO -PUEBLA S/N, SAL SALVADOR EL VERDE, SAN MARTIN TEXMELUCAN,",
                            IdMunicipio = new Guid("4ec19346-41d3-4e07-8731-6b9fdc68e976"),
                            Nombre = "CASA DE JUSTICIA SAN MARTÍN TEXMELUCAN "
                        },
                        new
                        {
                            Id = new Guid("f1923ee5-86b3-48c5-984a-5feba4f02581"),
                            Direccion = "CALLE VICENTE GUERRERO NO.714 COL, MORELOS SAN MARTIN TEXMELUCAN, CP.: 74020",
                            IdMunicipio = new Guid("4ec19346-41d3-4e07-8731-6b9fdc68e976"),
                            Nombre = "AGENCIA ESTATAL DE INVESTIGACION SAN MARTIN TEXMELUCAN "
                        },
                        new
                        {
                            Id = new Guid("b06b8873-efca-4b44-8b9c-13a830d2abb3"),
                            Direccion = "REFORMA 3 ORIENTE, COL. CENTRO 74000 SAN MARTIN TEXMELUCAN, PUE.",
                            IdMunicipio = new Guid("4ec19346-41d3-4e07-8731-6b9fdc68e976"),
                            Nombre = "CANACO SAN MARTIN TEXMELUCAN"
                        },
                        new
                        {
                            Id = new Guid("b6c62d0f-ca04-4675-8a7b-9ebfac840a0c"),
                            Direccion = "CUARTA FRACCIÓN RANCHO DE SAN JOSE ACTIPAC, COL. SAN PEDRO MEXICALTZINGO,",
                            IdMunicipio = new Guid("8cd95bf0-a260-4e8b-9306-126c117e76a3"),
                            Nombre = "TERRENO SAN JOSE ACTIPAN CHOLULA"
                        },
                        new
                        {
                            Id = new Guid("613e2684-b49a-4cec-aa4a-a863833635d8"),
                            Direccion = "CALLE HIDALGO NO. 701 COL. CENTRO, SAN PEDRO CHOLULA",
                            IdMunicipio = new Guid("8cd95bf0-a260-4e8b-9306-126c117e76a3"),
                            Nombre = "ARCHIVO DISTRITAL"
                        },
                        new
                        {
                            Id = new Guid("43eb3a2c-e1ea-45dd-8bc9-9082da8f5ab2"),
                            Direccion = "CALLE 15 NORTE SIN NÚMERO, SEGUNDO PISO, SAN MATÍAS COCOYOTLA, SAN PEDRO CHOLULA, PUE.",
                            IdMunicipio = new Guid("8cd95bf0-a260-4e8b-9306-126c117e76a3"),
                            Nombre = "UNIDAD DE INVESTIGACION SAN PEDRO CHOLULA"
                        },
                        new
                        {
                            Id = new Guid("7a7898ea-b1c6-4927-b759-25d61ac7dd22"),
                            Direccion = "AV. 4 ORIENTE SIN NUMERO TECOAC",
                            IdMunicipio = new Guid("22a067fb-bac4-42d9-89f4-54eaf6995a45"),
                            Nombre = "UNIDAD DE INVESTIGACION EL SECO"
                        },
                        new
                        {
                            Id = new Guid("e3a432ab-30cd-4d11-b25d-63bc469f267d"),
                            Direccion = "CALLE JOSE GALEANA NO. 200 COLONIA DOMINGO ARENAS, SANTA RITA TLAHUAPAN",
                            IdMunicipio = new Guid("f6b2c9a2-a8a0-457f-a618-f4fed4403ff6"),
                            Nombre = "AGENCIA ESTATAL DE INVESTIGACION SANTA RITA TLAHUAPAN "
                        },
                        new
                        {
                            Id = new Guid("2263367d-0dd3-48b4-8a6b-801b20495c12"),
                            Direccion = "CALLE MIGUEL HIDALGO S/N COL. CENTRO 74100, SANTA RITA TLAHUAPAN, PUE.",
                            IdMunicipio = new Guid("f6b2c9a2-a8a0-457f-a618-f4fed4403ff6"),
                            Nombre = "UNIDAD DE INVESTIGACION SANTA RITA TLAHUAPAN"
                        },
                        new
                        {
                            Id = new Guid("ec0684fb-691e-4461-a5e1-00c14dac3b02"),
                            Direccion = "11 PONIENTE ENTRE 1 SUR Y AV. NACIONAL, SANTIAGO MIAHUATLAN, PUE.",
                            IdMunicipio = new Guid("070dd2bb-10cf-411b-b5e5-fcaa42de9656"),
                            Nombre = "UNIDAD DE INVESTIGACION SANTIAGO MIAHUATLAN"
                        },
                        new
                        {
                            Id = new Guid("517d2546-abfd-48aa-8bc7-33c1873886fc"),
                            Direccion = "CALLE DE HERRERA S/N COL. CENTRO, TECALI DE HERRERA",
                            IdMunicipio = new Guid("8a115e57-7789-4db1-b4cd-961cc0cb50f8"),
                            Nombre = "UNIDAD DE INVESTIGACION TECALI DE HERRERA "
                        },
                        new
                        {
                            Id = new Guid("f3c5ed2b-980a-4590-ad5b-99677883bd1d"),
                            Direccion = "17 SUR NUMERO 304 COLONIA BARRIO DE ANALCO",
                            IdMunicipio = new Guid("8a115e57-7789-4db1-b4cd-961cc0cb50f8"),
                            Nombre = "AGENCIA ESTATAL DE INVESTIGACION"
                        },
                        new
                        {
                            Id = new Guid("e7c913cc-ea42-473c-9693-03873430a89b"),
                            Direccion = "CARRETERA FEDERAL KM 60+490, COL.SANTIAGO ALSESECA, TECAMACHALCO, CP.: 75480",
                            IdMunicipio = new Guid("16656bd5-ea70-46a9-adc2-acd89cc2fb63"),
                            Nombre = "CASA DE JUSTICIA TECAMACHALCO "
                        },
                        new
                        {
                            Id = new Guid("60468304-b094-46f8-9113-89bf24e222ed"),
                            Direccion = "CALLE 7 ORIENTE S/N COL. CENTRO, CP.: 75480",
                            IdMunicipio = new Guid("16656bd5-ea70-46a9-adc2-acd89cc2fb63"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS  TECAMACHALCO "
                        },
                        new
                        {
                            Id = new Guid("001890e1-494f-4bd0-8296-0844d17a52b2"),
                            Direccion = " A.V. GUERRERO ENTRE CALLE 31 SUR, Y CARRETERA A SAN MATEO TLAIXCAPAN",
                            IdMunicipio = new Guid("16656bd5-ea70-46a9-adc2-acd89cc2fb63"),
                            Nombre = "SEMEFO TECAMACHALCO "
                        },
                        new
                        {
                            Id = new Guid("29d78cdf-7d81-4434-87a7-d8a096fb5262"),
                            Direccion = "CALLE 10 SUR 507, BARRIO DE SAN JOSE, TECAMACHALCO, PUEBLA",
                            IdMunicipio = new Guid("16656bd5-ea70-46a9-adc2-acd89cc2fb63"),
                            Nombre = "UNIDAD DE INVESTIGACION TECAMACHALCO"
                        },
                        new
                        {
                            Id = new Guid("4f74a07c-dcc2-492f-b861-aa33f1c06f89"),
                            Direccion = "CALLE COMPLUTENSE ESQUINA CALLE DE LA TURBINA S/N COL. UNIVERSIDADES II, TEHUACAN ,PUE. CP.: 75723",
                            IdMunicipio = new Guid("829d477c-f775-4c88-9953-85d22ba08598"),
                            Nombre = "CENTRO DE JUSTICIA PARA LAS MUJERES TEHUACÁN "
                        },
                        new
                        {
                            Id = new Guid("86c1dc53-9781-4c00-9e35-435434182bb5"),
                            Direccion = "CARRETERA FEDERAL A TEHUACÁN KM 43+800",
                            IdMunicipio = new Guid("829d477c-f775-4c88-9953-85d22ba08598"),
                            Nombre = "ARCO DE SEGURIDAD DE CUAPIAXTLA DE MADERO "
                        },
                        new
                        {
                            Id = new Guid("551d631a-1bf3-4c74-8d31-339b2cf1b06e"),
                            Direccion = "BLVD. ADOLFO MATEOS NO.4, PLANTA ALTA, COL. ZONA ALTA, TEHUACAN, PUEBLA CP.: 75750",
                            IdMunicipio = new Guid("829d477c-f775-4c88-9953-85d22ba08598"),
                            Nombre = "CASA DE JUSTICIA TEHUACÁN "
                        },
                        new
                        {
                            Id = new Guid("3c68d977-b39e-42ba-8cdb-32b755568792"),
                            Direccion = "CARRETERA FEDERAL PUEBLA - TEHUACÁN KILOMETRO 114, MANANTIALES, TEHUACÁN, PUE. CP.: 75855",
                            IdMunicipio = new Guid("829d477c-f775-4c88-9953-85d22ba08598"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS TEHUACAN "
                        },
                        new
                        {
                            Id = new Guid("dae3d229-4207-429c-9e57-f8cccc6ee315"),
                            Direccion = "CARRETERA FEDERAL PUEBLA TEHUACAN 1211 O KM 114 SAN LORENZO TEOTIPILCO, TEHUACAN, PUE.",
                            IdMunicipio = new Guid("829d477c-f775-4c88-9953-85d22ba08598"),
                            Nombre = "C5 TEHUACAN"
                        },
                        new
                        {
                            Id = new Guid("a39ac9f9-c924-45b9-b1be-267666325a32"),
                            Direccion = "CALZADA ADOLFO LÓPEZ MATEOS NO.3210 LOCAL 21A, COL.ZONA ALTA TEHUACAN, PUEBLA, CP.: 75750",
                            IdMunicipio = new Guid("829d477c-f775-4c88-9953-85d22ba08598"),
                            Nombre = "INSTITUTO DE CIENCIAS FORENSES TEHUACAN "
                        },
                        new
                        {
                            Id = new Guid("7312e9c9-0580-405e-a888-5143fe0dd037"),
                            Direccion = "CALLE 19 PONIENTE SIN NUMERO PANTEON MUNICIPAL, TEHUACAN PUEBLA",
                            IdMunicipio = new Guid("829d477c-f775-4c88-9953-85d22ba08598"),
                            Nombre = "SEMEFO TEHUACAN "
                        },
                        new
                        {
                            Id = new Guid("a1908d9e-faa2-4a56-9f11-2dea75caa8d8"),
                            Direccion = "CALLE LA PRESA SECCIÓN TERCERA, TEHUITZINGO , PUEBLA ",
                            IdMunicipio = new Guid("69dd05ed-5bb1-4f47-bc2c-ee48f63e2339"),
                            Nombre = "UNIDAD DE INVESTIGACION TEHUITZINGO"
                        },
                        new
                        {
                            Id = new Guid("eec8040b-0e53-4e24-943a-3918698d83f3"),
                            Direccion = "PRIV. 8 PONIENTE S/N COL. CENTRO 75800, TEPANCO DE LOPEZ, PUE.",
                            IdMunicipio = new Guid("c7fd150d-2594-4b43-baed-cbdd53be44d6"),
                            Nombre = "UNIDAD DE INVESTIGACION TEPANCO"
                        },
                        new
                        {
                            Id = new Guid("639b4773-ad67-4cfe-9fae-4fdb68abcbe8"),
                            Direccion = "2 SUR ESQUINA CON 9 ORIENTE S/N COL. CENTRO, TEPATLAXCO DE HIDALGO, PRIMER PISO",
                            IdMunicipio = new Guid("5910d6e7-8c16-4598-9630-1f59d48a71d7"),
                            Nombre = "UNIDAD DE INVESTIGACION TEPATLAXCO"
                        },
                        new
                        {
                            Id = new Guid("dc69dab8-8924-4f3b-baca-135fa879ead5"),
                            Direccion = "AVENIDA HIDALGO NÚMERO 509 A, TEPEACA PUEBLA",
                            IdMunicipio = new Guid("d5b17b0b-1b1c-4b65-983d-113ad6d561fb"),
                            Nombre = "UNIDAD DE INVESTIGACIÓN TEPEACA"
                        },
                        new
                        {
                            Id = new Guid("eefb8302-4983-458b-baa9-b524aebd8ee3"),
                            Direccion = "INTERIOR DEL PANTEON MUNICIPAL, CALLE 17 ORIENTE Y AVENIDA COLON SIN NUMERO, BARRIO EL  SANTUARIO  ",
                            IdMunicipio = new Guid("d5b17b0b-1b1c-4b65-983d-113ad6d561fb"),
                            Nombre = "SEMEFO TEPEACA "
                        },
                        new
                        {
                            Id = new Guid("3e4a271f-71db-4e3b-a940-15376681ff4a"),
                            Direccion = "CALLE IRINEO VAZQUEZ, NÚMERO 1, TEPEOJUMA, PUEBLA",
                            IdMunicipio = new Guid("b62bfed7-4c62-41e0-bfb2-10ca87db6e91"),
                            Nombre = "UNIDAD DE INVESTIGACION TEPEOJUMA"
                        },
                        new
                        {
                            Id = new Guid("2102c0c8-e76f-49ad-a3dd-6c25cc19a08f"),
                            Direccion = "CUAPIXTLA - ACATLÁN DE OSORIO NO. 35 SAN SEBASTIAN DE TEPEXI DE RODRIGUEZ , PUE.",
                            IdMunicipio = new Guid("d94a72c8-8670-4344-ab47-a78c2fefadef"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS  TEPEXI DE RODRÍGUEZ "
                        },
                        new
                        {
                            Id = new Guid("95f5f5dc-acf5-4fc5-bb10-ccd0555f8d9f"),
                            Direccion = "CALLE 5 DE FEBRERO PLAZA COMUNITARIA PROF .ABEL CRUZ GARCIA , NÚMERO 3  COL CENTRO, TEPEXI DE RODRIGUEZ PUEBLA",
                            IdMunicipio = new Guid("d94a72c8-8670-4344-ab47-a78c2fefadef"),
                            Nombre = "UNIDAD DE INVESTIGACION TEPEXI DE RODRÍGUEZ "
                        },
                        new
                        {
                            Id = new Guid("599ac965-a47e-4888-bc63-a300affb0a65"),
                            Direccion = "PANTEON MUNICIPAL CALLE DEFENSORES DEL 6 DE JUNIO SIN NUMERO, TEPEXI DE  RODRIGUEZ ",
                            IdMunicipio = new Guid("d94a72c8-8670-4344-ab47-a78c2fefadef"),
                            Nombre = "SEMEFO TEPEXI DE RODRIGUEZ "
                        },
                        new
                        {
                            Id = new Guid("e5f1bd4c-23dd-45a4-beb8-51579069b684"),
                            Direccion = "CALLE PRIMERA DE VENUSTIANO CARRANZA Y CALLE PRIMERA MORELOS S/N TEPEYAHUALCO, PUE.",
                            IdMunicipio = new Guid("088e4526-c5b8-442b-aa82-96d5c4bb294b"),
                            Nombre = "UNIDAD DE INVESTIGACION TEPEYAHUALCO"
                        },
                        new
                        {
                            Id = new Guid("e13e1af5-0f02-4f15-8607-f4b45d94b0c0"),
                            Direccion = "7 PONIENTE #1, COLONIA CENTRO, TETELA DE OCAMPO, PUEBLA",
                            IdMunicipio = new Guid("609ebfc5-4b53-46b3-95d5-00d1952f7509"),
                            Nombre = "UNIDAD DE INVESTIGACION TETELA DE OCAMPO"
                        },
                        new
                        {
                            Id = new Guid("2698e8f1-6a18-4df2-919a-acb2f4ecf72d"),
                            Direccion = "CALLE LA MESILLA NO.10 COL. INDUSTRIAL, TEZIUTLÁN, PUEBLA. CP.: 73850",
                            IdMunicipio = new Guid("815dd755-5c1b-440f-90eb-52c6640f873c"),
                            Nombre = "CASA DE JUSTICIA TEZIUTLÁN"
                        },
                        new
                        {
                            Id = new Guid("05f6286f-d7cc-4542-a83f-ba0833e8f1d6"),
                            Direccion = "AV HIDALGO NO.169 EDIFICIO REAL PLANTA BAJA, CENTRO. TEZIUTLAN, PUEBLA.",
                            IdMunicipio = new Guid("815dd755-5c1b-440f-90eb-52c6640f873c"),
                            Nombre = "CENTRO INTEGRAL  DE SERVICIOS  TEZIUTLÁN "
                        },
                        new
                        {
                            Id = new Guid("b36b6895-a454-4783-a2bf-5440af2e518f"),
                            Direccion = "CALLE LERDO NÚMERO 205, ALTOS COL. CENTRO. ANEXO AL CERESO, TEZIUTLAN , PUEBLA",
                            IdMunicipio = new Guid("815dd755-5c1b-440f-90eb-52c6640f873c"),
                            Nombre = "AGENCIA ESTATAL DE INVESTIGACION"
                        },
                        new
                        {
                            Id = new Guid("683c08ea-a693-4ec9-91c5-63c930e0e9ff"),
                            Direccion = "CALLE COSTADO SUR DEL PANTEON MUNICIPAL, SIN NUMERO, TEZIUTLAN, PUEBLA ",
                            IdMunicipio = new Guid("815dd755-5c1b-440f-90eb-52c6640f873c"),
                            Nombre = "SEMEFO TEZIUTLAN"
                        },
                        new
                        {
                            Id = new Guid("40d44739-fb45-46c1-9d05-f18ed2e89d7d"),
                            Direccion = "PLAZA COMUNITARIA CALLE AGUASCALIENTES SIN NUMERO COLONIA CENTRO 75680",
                            IdMunicipio = new Guid("e455c8ee-fe22-4913-a6c0-2b206e2cc8e8"),
                            Nombre = "UNIDAD DE INVESTIGACION TLACOTEPEC"
                        },
                        new
                        {
                            Id = new Guid("0a40dfbd-a88e-4d5f-b295-d4a74ddf7f75"),
                            Direccion = "REAL DE SAN PEDRO NO 15 COL. CENTRO, C.P.72600, TLALTENANGO, PUE.",
                            IdMunicipio = new Guid("3a74ce88-ba94-4988-bb2b-434a9c208d28"),
                            Nombre = "UNIDAD DE INVESTIGACION TLALTENANGO "
                        },
                        new
                        {
                            Id = new Guid("1705e288-eb03-424e-af0c-b9f479f33d15"),
                            Direccion = "ESQUINA QUE FORMAN LAS CALLES MORELOS Y CUAUHTEMOC NÚMERO 1, TLAOLA, PUEBLA",
                            IdMunicipio = new Guid("71222470-32e9-4f76-ba77-6af9e2c98d57"),
                            Nombre = "UNIDAD DE INVESTIGACION TLAOLA"
                        },
                        new
                        {
                            Id = new Guid("aac51693-cc42-49e8-960b-579e9b468444"),
                            Direccion = "PALACION MUNICIPAL S/N TLAPANALA PUEBLA",
                            IdMunicipio = new Guid("a68b6bb8-07ea-49a9-bf68-2cec60a131ce"),
                            Nombre = "UNIDAD DE INVESTIGACION TLAPANALA"
                        },
                        new
                        {
                            Id = new Guid("1f43c704-5596-4ded-a0b5-59d93fc19498"),
                            Direccion = "CARRETERA FEDERAL TEZIUTLAN - ACAJETE NO. 169 BARRIO DE CONTLA",
                            IdMunicipio = new Guid("34b45ec0-f95a-48aa-8fdb-cb3cd43849a7"),
                            Nombre = "CENTRO INTEGRAL DE SERVICIOS  TLATLAUQUITEPEC "
                        },
                        new
                        {
                            Id = new Guid("f70ef1ad-0094-4119-8c6c-53399b848bcc"),
                            Direccion = "AV. INDEPENDENCIA NUM. 20 COL.CENTRO , TLATLAUQUITEPEC,PUEBLA",
                            IdMunicipio = new Guid("34b45ec0-f95a-48aa-8fdb-cb3cd43849a7"),
                            Nombre = "AGENCIA ESTATAL DE INVESTIGACION"
                        },
                        new
                        {
                            Id = new Guid("fea64774-60ed-4923-bb38-309168159be6"),
                            Direccion = "AV DOLORES BETANCOURT COL. CONTLA, TLATLAUQUITEPEC, PUEBLA ",
                            IdMunicipio = new Guid("34b45ec0-f95a-48aa-8fdb-cb3cd43849a7"),
                            Nombre = "SEMEFO TLATLAUQUITEPEC "
                        },
                        new
                        {
                            Id = new Guid("c00a403c-dd28-4684-8794-b8ea2c5bb364"),
                            Direccion = "CARRETERA FEDERAL PACHUCA TUXPAN, COL. CENTRO, VILLA LÁZARO CARDENAS",
                            IdMunicipio = new Guid("7cd8ed93-5d81-451f-80ad-314a359c9881"),
                            Nombre = "UNIDAD DE INVESTIGACION LAZARO CARDENAS"
                        },
                        new
                        {
                            Id = new Guid("1da44cbe-4719-4cc7-8103-ce7b9c853617"),
                            Direccion = "CALLE FCO. JAVIER MINA NO. 303, COL. LA RIVERA XICOTEPEC DE JUAREZ, PUE. CP.: 73080",
                            IdMunicipio = new Guid("8e77a494-ce8b-4500-b883-cb24e774d350"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS  XICOTEPEC DE JUAREZ"
                        },
                        new
                        {
                            Id = new Guid("a4eced61-5cf3-4047-b6b5-ca7413f818c7"),
                            Direccion = "CALLE 2 DE ABRIL 117 COLONIA CENTRO, XICOTEPEC DE JUAREZ, PUEBLA.",
                            IdMunicipio = new Guid("8e77a494-ce8b-4500-b883-cb24e774d350"),
                            Nombre = "UNIDAD DE INVESTIGACION XICOTEPEC DE JUAREZ"
                        },
                        new
                        {
                            Id = new Guid("8b820905-8270-44e7-afc0-13d9eabb77d5"),
                            Direccion = "AV. ZARAGOZA SIN NUMERO, XICOTEPEC DE JUAREZ  ",
                            IdMunicipio = new Guid("8e77a494-ce8b-4500-b883-cb24e774d350"),
                            Nombre = "SEMEFO XICOTEPEC DE JUAREZ"
                        },
                        new
                        {
                            Id = new Guid("6b9fbf34-f812-4502-ac14-eff4c9241f47"),
                            Direccion = "CALLE 2 DE ABRIL SUR, EDIFICIO REVOLUCIÓN ESQUINA IGNACIO COETO ,COL. CENTRO ZACAPOAXTLA PUEBLA",
                            IdMunicipio = new Guid("7ec98118-cd95-440e-ae88-3e8fbb68486b"),
                            Nombre = "UNIDAD DE INVESTIGACION ZACAPOAXTLA"
                        },
                        new
                        {
                            Id = new Guid("c09b9fdb-c701-455e-9122-646fe89d7561"),
                            Direccion = "CALLE 2 DE ABRIL NORTE  SIN NUMERO ESQUINA FJ. ARRIAGA COL. CENTRO ZACAPOAXTLA, PUEBLA ",
                            IdMunicipio = new Guid("7ec98118-cd95-440e-ae88-3e8fbb68486b"),
                            Nombre = "SEMEFO ZACAPOAXTLA "
                        },
                        new
                        {
                            Id = new Guid("02d42a2c-869f-4a86-a656-61f5442a4d8c"),
                            Direccion = "LIBRAMIENTO CARRETERA ZACATLAN -TEJOCOTAL, BARRIO DE MAQUIXTLA, ZACATLAN, PUEBLA CP.: 73310",
                            IdMunicipio = new Guid("768aff2f-8946-45ff-ba24-d0065b01b7de"),
                            Nombre = "UNIDAD DE INVESTIGACIÓN CRIMINAL  Y UNIDAD DE ATENCIÓN TEMPRANA ZACATLAN"
                        },
                        new
                        {
                            Id = new Guid("967a8b5a-7e85-4cab-bc1c-365861402c87"),
                            Direccion = "COLONIA 2 CAMINOS ZACATLÁN , PUE. BARRIO TECOJOTAL, CP.: 73310",
                            IdMunicipio = new Guid("768aff2f-8946-45ff-ba24-d0065b01b7de"),
                            Nombre = "CENTRO INTEGRAL SERVICIOS ZACATLÁN "
                        },
                        new
                        {
                            Id = new Guid("fdf2ff41-ab3f-4ea6-b116-fd40da4564f2"),
                            Direccion = "CALLE PORFIRIO DIAZ Y DOLORES PEREZ SIN NUMERO COL. CENTRO  ZACATLAN, PUEBLA",
                            IdMunicipio = new Guid("768aff2f-8946-45ff-ba24-d0065b01b7de"),
                            Nombre = "SEMEFO ZACATLAN"
                        },
                        new
                        {
                            Id = new Guid("fed305e2-327f-4d6c-acb4-6f7eea552c76"),
                            Direccion = "CALLE 3 ORIENTE 1211 COLONIA SANTA ANA, ZARAGOZA, PUE.",
                            IdMunicipio = new Guid("d62af5ec-82e5-4515-8e19-04c8a10c9161"),
                            Nombre = "UNIDAD DE INVESTIGACION ZARAGOZA"
                        },
                        new
                        {
                            Id = new Guid("c013a797-be80-4f35-93ab-960194430f21"),
                            Direccion = "CALLE JUVENTUD S/N COL. CENTRO",
                            IdMunicipio = new Guid("b6532a44-f248-4575-ba87-b6374cf2322f"),
                            Nombre = "UNIDAD DE INVESTIGACION ZOQUITLAN"
                        });
                });

            modelBuilder.Entity("ControlAsistencia_.Models.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Municipio");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b476639-85d3-4931-9394-3d10b3b40648"),
                            Nombre = "ACAJETE"
                        },
                        new
                        {
                            Id = new Guid("883fd478-e136-4504-a096-1b8d30ab8639"),
                            Nombre = "ACATENO"
                        },
                        new
                        {
                            Id = new Guid("b8c23bfb-5297-4c64-b49d-6bcaa97f1d12"),
                            Nombre = "ACATLAN DE OSORIO"
                        },
                        new
                        {
                            Id = new Guid("0ddfe43e-a48a-4f89-bce3-ce093d05c35f"),
                            Nombre = "ACATZINGO"
                        },
                        new
                        {
                            Id = new Guid("7c58f0ba-3d86-4743-a359-75df6fdbc64f"),
                            Nombre = "AHUAZOTEPEC"
                        },
                        new
                        {
                            Id = new Guid("4b97a0d5-3da2-4a2c-97e5-eb0ed561299d"),
                            Nombre = "AJALPAN"
                        },
                        new
                        {
                            Id = new Guid("0c53a94f-3779-46b9-aa25-1bfe43c046e4"),
                            Nombre = "ALTEPEXI"
                        },
                        new
                        {
                            Id = new Guid("c95ce227-0ffa-4eae-b23e-bdd3c19bc822"),
                            Nombre = "AMOZOC"
                        },
                        new
                        {
                            Id = new Guid("c5c10ff1-a75c-432e-b5df-96086cdfe47b"),
                            Nombre = "ATEMPAN"
                        },
                        new
                        {
                            Id = new Guid("61203fd8-1089-478e-8061-78d51358c7ad"),
                            Nombre = "ATENCINGO"
                        },
                        new
                        {
                            Id = new Guid("0297d60e-31e1-4cb7-973a-a9f9104e7dc9"),
                            Nombre = "ATLIXCO"
                        },
                        new
                        {
                            Id = new Guid("974ec286-e9d0-4ddd-9adb-60e0364c8a9c"),
                            Nombre = "CALPAN"
                        },
                        new
                        {
                            Id = new Guid("f751758f-84ad-43ad-a5d5-b51400ffa92c"),
                            Nombre = "CHALCHICOMULA DE SESMA"
                        },
                        new
                        {
                            Id = new Guid("a4662e9d-4c5b-4fa3-803c-6ab3e0e0b7cc"),
                            Nombre = "CHALCHIHUAPAN"
                        },
                        new
                        {
                            Id = new Guid("76a59c1c-6538-4a5b-9d55-4ed081309a70"),
                            Nombre = "CHIAUTLA DE TAPIA"
                        },
                        new
                        {
                            Id = new Guid("6dc36e6e-8182-4a61-8c1a-83d03d36a673"),
                            Nombre = "CHIETLA"
                        },
                        new
                        {
                            Id = new Guid("796fe037-7c39-48a1-be38-3d883e228409"),
                            Nombre = "CHIGNAHUAPAN"
                        },
                        new
                        {
                            Id = new Guid("4aef29cc-0f44-4e25-a704-902804424e41"),
                            Nombre = "CORONANGO"
                        },
                        new
                        {
                            Id = new Guid("9005ddce-0399-4cab-8496-456b816bcfeb"),
                            Nombre = "CUAUTLANCINGO"
                        },
                        new
                        {
                            Id = new Guid("54870e6a-687e-4ed5-8882-e6cc3d2f3a3c"),
                            Nombre = "CUETZALAN DEL PROGRESO"
                        },
                        new
                        {
                            Id = new Guid("51d0e71c-1ce2-4874-8eeb-57080ca1bd7b"),
                            Nombre = "ESPERANZA"
                        },
                        new
                        {
                            Id = new Guid("3910b3bd-9281-4568-bda3-942a24c94b9c"),
                            Nombre = "GUADALUPE VICTORIA"
                        },
                        new
                        {
                            Id = new Guid("2d3de914-b664-4219-9faa-675431c332b7"),
                            Nombre = "HUAUCHINANGO"
                        },
                        new
                        {
                            Id = new Guid("2603582a-751a-4fbc-8391-e6168f3afafc"),
                            Nombre = "HUEHUETLA"
                        },
                        new
                        {
                            Id = new Guid("57fc7f0d-f60d-4b2b-a9aa-eacb174d7592"),
                            Nombre = "HUEJOTZINGO"
                        },
                        new
                        {
                            Id = new Guid("c0a081c3-7bb4-49a6-80a5-c0ab374fe23b"),
                            Nombre = "HUEYTAMALCO"
                        },
                        new
                        {
                            Id = new Guid("d26d3ce6-9743-497b-a8f3-f267e49918fb"),
                            Nombre = "IZUCAR DE MATAMOROS"
                        },
                        new
                        {
                            Id = new Guid("efcddcba-b5d6-4331-b9de-5a80228c3327"),
                            Nombre = "JUAN C. BONILLA"
                        },
                        new
                        {
                            Id = new Guid("9a631574-5367-4dbe-b233-d9b4fa2d4cc3"),
                            Nombre = "LIBRES"
                        },
                        new
                        {
                            Id = new Guid("e6c3c45c-9c22-4949-a697-2861723754ea"),
                            Nombre = "LOS REYES DE JUAREZ"
                        },
                        new
                        {
                            Id = new Guid("13e0d93f-8bad-4e1a-98fd-5c9f1b28e1c1"),
                            Nombre = "METLALTOYUCA"
                        },
                        new
                        {
                            Id = new Guid("e7b9f2d3-0fdc-4659-8e39-f1afe19616a2"),
                            Nombre = "OCOYUCAN"
                        },
                        new
                        {
                            Id = new Guid("dc6cdefc-c85a-48cc-8903-c4f6667d3feb"),
                            Nombre = "ORIENTAL"
                        },
                        new
                        {
                            Id = new Guid("45d33258-4f97-4ced-99a1-467449ef159d"),
                            Nombre = "PALMAR DE BRAVO"
                        },
                        new
                        {
                            Id = new Guid("4fd1f509-0631-4439-bf51-fb8dfc615fa5"),
                            Nombre = "PIAXTLA"
                        },
                        new
                        {
                            Id = new Guid("d708e960-e465-4b40-9f31-1c97c21d5b8a"),
                            Nombre = "PUEBLA"
                        },
                        new
                        {
                            Id = new Guid("53c9635e-f7a6-45dc-a252-d1cd45d5f42c"),
                            Nombre = "SAN ANDRES CHOLULA"
                        },
                        new
                        {
                            Id = new Guid("a7dd00ae-a69c-4b94-9b44-d09029d2e493"),
                            Nombre = "SAN GABRIEL CHILAC"
                        },
                        new
                        {
                            Id = new Guid("26935263-7f17-4db2-bfb7-908cd3cbad54"),
                            Nombre = "SAN JOSE CHIAPA"
                        },
                        new
                        {
                            Id = new Guid("4ec19346-41d3-4e07-8731-6b9fdc68e976"),
                            Nombre = "SAN MARTIN TEXMELUCAN"
                        },
                        new
                        {
                            Id = new Guid("8cd95bf0-a260-4e8b-9306-126c117e76a3"),
                            Nombre = "SAN PEDRO CHOLULA"
                        },
                        new
                        {
                            Id = new Guid("22a067fb-bac4-42d9-89f4-54eaf6995a45"),
                            Nombre = "SAN SALVADOR EL SECO"
                        },
                        new
                        {
                            Id = new Guid("f6b2c9a2-a8a0-457f-a618-f4fed4403ff6"),
                            Nombre = "SANTA RITA TLAHUAPAN"
                        },
                        new
                        {
                            Id = new Guid("070dd2bb-10cf-411b-b5e5-fcaa42de9656"),
                            Nombre = "SANTIAGO MIAHUATLAN"
                        },
                        new
                        {
                            Id = new Guid("8a115e57-7789-4db1-b4cd-961cc0cb50f8"),
                            Nombre = "TECALI DE HERRERA"
                        },
                        new
                        {
                            Id = new Guid("16656bd5-ea70-46a9-adc2-acd89cc2fb63"),
                            Nombre = "TECAMACHALCO"
                        },
                        new
                        {
                            Id = new Guid("829d477c-f775-4c88-9953-85d22ba08598"),
                            Nombre = "TEHUACAN"
                        },
                        new
                        {
                            Id = new Guid("69dd05ed-5bb1-4f47-bc2c-ee48f63e2339"),
                            Nombre = "TEHUITZINGO"
                        },
                        new
                        {
                            Id = new Guid("c7fd150d-2594-4b43-baed-cbdd53be44d6"),
                            Nombre = "TEPANCO DE LOPEZ"
                        },
                        new
                        {
                            Id = new Guid("5910d6e7-8c16-4598-9630-1f59d48a71d7"),
                            Nombre = "TEPATLAXCO DE HIDALGO"
                        },
                        new
                        {
                            Id = new Guid("d5b17b0b-1b1c-4b65-983d-113ad6d561fb"),
                            Nombre = "TEPEACA"
                        },
                        new
                        {
                            Id = new Guid("b62bfed7-4c62-41e0-bfb2-10ca87db6e91"),
                            Nombre = "TEPEOJUMA"
                        },
                        new
                        {
                            Id = new Guid("d94a72c8-8670-4344-ab47-a78c2fefadef"),
                            Nombre = "TEPEXI DE RODRIGUEZ"
                        },
                        new
                        {
                            Id = new Guid("088e4526-c5b8-442b-aa82-96d5c4bb294b"),
                            Nombre = "TEPEYAHUALCO"
                        },
                        new
                        {
                            Id = new Guid("609ebfc5-4b53-46b3-95d5-00d1952f7509"),
                            Nombre = "TETELA DE OCAMPO"
                        },
                        new
                        {
                            Id = new Guid("815dd755-5c1b-440f-90eb-52c6640f873c"),
                            Nombre = "TEZIUTLAN"
                        },
                        new
                        {
                            Id = new Guid("e455c8ee-fe22-4913-a6c0-2b206e2cc8e8"),
                            Nombre = "TLACOTEPEC DE BENITO JUAREZ"
                        },
                        new
                        {
                            Id = new Guid("3a74ce88-ba94-4988-bb2b-434a9c208d28"),
                            Nombre = "TLALTENANGO"
                        },
                        new
                        {
                            Id = new Guid("71222470-32e9-4f76-ba77-6af9e2c98d57"),
                            Nombre = "TLAOLA"
                        },
                        new
                        {
                            Id = new Guid("a68b6bb8-07ea-49a9-bf68-2cec60a131ce"),
                            Nombre = "TLAPANALA"
                        },
                        new
                        {
                            Id = new Guid("34b45ec0-f95a-48aa-8fdb-cb3cd43849a7"),
                            Nombre = "TLATLAUQUITEPEC"
                        },
                        new
                        {
                            Id = new Guid("7cd8ed93-5d81-451f-80ad-314a359c9881"),
                            Nombre = "VILLA LAZARO CARDENAS"
                        },
                        new
                        {
                            Id = new Guid("8e77a494-ce8b-4500-b883-cb24e774d350"),
                            Nombre = "XICOTEPEC DE JUAREZ"
                        },
                        new
                        {
                            Id = new Guid("7ec98118-cd95-440e-ae88-3e8fbb68486b"),
                            Nombre = "ZACAPOAXTLA"
                        },
                        new
                        {
                            Id = new Guid("768aff2f-8946-45ff-ba24-d0065b01b7de"),
                            Nombre = "ZACATLAN"
                        },
                        new
                        {
                            Id = new Guid("d62af5ec-82e5-4515-8e19-04c8a10c9161"),
                            Nombre = "ZARAGOZA"
                        },
                        new
                        {
                            Id = new Guid("b6532a44-f248-4575-ba87-b6374cf2322f"),
                            Nombre = "ZOQUITLAN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
