using ControlAsistencia_.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DBContext
{
    public class ControlAsistenciaDBContext : DbContext
    {
        public ControlAsistenciaDBContext(DbContextOptions options) : base(options) { }

        public DbSet<Asistencia> Asistencia { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Inmueble> Inmueble { get; set; }
        public DbSet<Municipio> Municipio { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Asistencia>(entity =>
            {
                entity.HasKey(e => e.Id);
            });

            modelBuilder.Entity<Empleado>(entity =>
            {
                entity.HasKey(e => e.Id);
            });

            modelBuilder.Entity<Inmueble>(entity =>
            {
                entity.HasKey(e => e.Id);
            });

            modelBuilder.Entity<Municipio>(entity =>
            {
                entity.HasKey(e => e.Id);
            });

            //Catalogo Municipios

            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("c9f813a7-03b9-43bd-9108-b8f9e6eb180a"), Nombre = "ACAJETE" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("d610cb1b-ae13-4233-973a-576d17007086"), Nombre = "ACATENO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("f62bb8c8-4b37-45ba-84c0-5793db11cd6c"), Nombre = "ACATLAN DE OSORIO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("619cf7b3-26e4-4e57-a250-63dc062944fc"), Nombre = "ACATZINGO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("59f44ef4-f5b1-428d-93c6-70a910ad2f00"), Nombre = "AHUAZOTEPEC" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("bd07f47c-52c2-4021-a578-b591b69e1c22"), Nombre = "AJALPAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("6e9d1d95-ca7f-47f6-99a7-77aa3394d86a"), Nombre = "ALTEPEXI" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("7fca1562-06f8-4884-a0c9-7728871d5575"), Nombre = "AMOZOC" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("1662c16e-7e4d-4d3e-8f41-7dedd5d6e492"), Nombre = "ATEMPAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("08828c72-9e07-480a-aadf-437f7a61eae7"), Nombre = "ATENCINGO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("d01cf41a-e3df-40ca-8fe6-2b97e5eff45c"), Nombre = "ATLIXCO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("f8a750e5-69d6-4852-accc-776883f0d482"), Nombre = "ATLIXCO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("62d84a1c-8101-4b6c-b170-fe01d8766196"), Nombre = "CALPAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("f9f94b35-2053-48d9-a6f0-45b8d25fa27e"), Nombre = "CHALCHICOMULA DE SESMA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("4ea92974-4462-4d84-bc3b-3f7c61a2f555"), Nombre = "CHALCHIHUAPAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("787facb0-7bc1-41b8-968f-4eb31ca20c97"), Nombre = "CHIAUTLA DE TAPIA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("b117f2a6-5d64-4acf-869a-8372887e2001"), Nombre = "CHIETLA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("74d08916-2f6d-4567-9842-de35a61936fd"), Nombre = "CHIGNAHUAPAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("474de62e-3fff-4411-b5b1-4083d40d58c8"), Nombre = "CORONANGO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("b4fe9dc9-ead3-4157-8e31-ae1c1161fa03"), Nombre = "CUAUTLANCINGO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("7117041c-d339-489f-81d2-fe6a286216a8"), Nombre = "CUETZALAN DEL PROGRESO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("070b655b-6ae1-4521-b632-62f3bed053ea"), Nombre = "ESPERANZA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("0013aaa9-9aa4-4536-8883-20ecc00101ac"), Nombre = "GUADALUPE VICTORIA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("4052d1a8-9e03-465d-8ef5-876b683b2446"), Nombre = "HUAUCHINANGO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("efb36764-3a04-4fbe-8101-01d312a093d4"), Nombre = "HUEHUETLA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("1329134d-6402-4744-8ccb-3a50d6356942"), Nombre = "HUEJOTZINGO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("5aff4322-56f1-4ce3-a3f6-fc73f16b179e"), Nombre = "HUEYTAMALCO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("3dfe6ba0-8ce2-4708-afcc-00c920a71ff2"), Nombre = "IZUCAR DE MATAMOROS" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("3335e17a-9aca-4d40-87c9-cb3b84968e86"), Nombre = "JUAN C. BONILLA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("44ee7bdb-414d-4fbc-95e9-610da19ebe30"), Nombre = "LIBRES" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("48d2806e-a9f5-4112-8af4-193dfac47181"), Nombre = "LIBRES" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("84b66dde-82bb-4f4c-8ce3-8f60be66717f"), Nombre = "LOS REYES DE JUAREZ" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("d8fbe709-e007-4925-b43d-ead21145e1c0"), Nombre = "METLALTOYUCA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("6fbeee9d-ac38-4c23-ae72-50975fcbdabf"), Nombre = "OCOYUCAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("017c3116-24fe-4b19-8502-ec226ee4cc2f"), Nombre = "ORIENTAL" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("b23b3d61-5778-4c8d-9279-234ca1aa5289"), Nombre = "PALMAR DE BRAVO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("c4fb8189-504c-41ef-ab9d-41cd1e47a83c"), Nombre = "PIAXTLA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("8a9cd5c0-ce59-4aa9-a39e-0a90768a4c75"), Nombre = "PUEBLA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("625cb731-9c3d-4991-91d5-ed17f8e3b281"), Nombre = "SAN ANDRES CHOLULA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("ac17232a-98d7-4595-a934-83b07ed7b50d"), Nombre = "SAN GABRIEL CHILAC" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("e53bc18e-9eae-42b6-8854-3a7ad6a34cf6"), Nombre = "SAN JOSE CHIAPA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("c8138d0a-8827-42e9-927a-a56cf73993f3"), Nombre = "SAN MARTIN TEXMELUCAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("b3db85e7-46cb-42cf-9f42-6249a2a7d7b9"), Nombre = "SAN PEDRO CHOLULA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("93a903b1-0328-4b8d-a4ce-3b361d3a7a00"), Nombre = "SAN SALVADOR EL SECO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("8fa9a48b-ecc3-4bde-9344-754ad1cf933c"), Nombre = "SANTA RITA TLAHUAPAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("d2297d02-c90f-4d22-9d13-be14ceb9d61c"), Nombre = "SANTIAGO MIAHUATLAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("0ffa61ec-b01d-4325-96fc-550e7f9e8019"), Nombre = "TECALI DE HERRERA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("356f5e0b-8ed5-4618-abc7-39f04f8991ee"), Nombre = "TECAMACHALCO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("8165f8fb-cbb9-4e13-af98-4113fbc596dd"), Nombre = "TEHUACAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("8f71402e-1c82-4e2c-8bdf-97276907da21"), Nombre = "TEHUACAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("655ce882-2770-43ff-9297-8d05db0d8643"), Nombre = "TEHUITZINGO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("e9853bc4-5636-4661-8204-59c68f6f5e42"), Nombre = "TEPANCO DE LOPEZ" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("63bd3d7e-9c57-401b-a648-7d0dbbc2d98d"), Nombre = "TEPATLAXCO DE HIDALGO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("6491ced6-e82d-4430-b194-2e22430d7716"), Nombre = "TEPEACA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("d60b66ed-9879-447f-9132-0211740015d7"), Nombre = "TEPEACA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("20e9951a-0315-4a64-a704-e9bc57d069be"), Nombre = "TEPEOJUMA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("9abe3d68-857d-4d15-9632-3938ac1687ad"), Nombre = "TEPEXI DE RODRIGUEZ" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("f2676294-47b2-4a74-9ea9-e058902ce295"), Nombre = "TEPEYAHUALCO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("ac3e8037-9f41-4431-b6ce-bce1ad0d4563"), Nombre = "TETELA DE OCAMPO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("9449ffb9-d4ce-49d4-b88b-478cbcf6dbce"), Nombre = "TEZIUTLAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("ecc0e511-9ad2-4f1f-a0e7-a98770d24c7c"), Nombre = "TEZIUTLAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("7220a0a0-b116-410d-bb3e-df3b66ce5957"), Nombre = "TLACOTEPEC DE BENITO JUAREZ" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("88468efe-9c46-4517-bcee-34a34e2b3b46"), Nombre = "TLALTENANGO" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("ba9683b2-acd5-46ed-9ddb-19b748d159f7"), Nombre = "TLAOLA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("f1efd7e9-0352-4b0f-ad1e-8085d72f72b9"), Nombre = "TLAPANALA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("03d93cb2-c1df-4dfe-aea0-1da37b7f8dae"), Nombre = "TLATLAUQUITEPEC" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("bcd17f17-eed5-4cb2-8496-52268566b6c3"), Nombre = "VILLA LAZARO CARDENAS" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("73119cc6-49ac-4228-a4a9-64db4776744c"), Nombre = "XICOTEPEC DE JUAREZ" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("29a9d23c-271a-443f-8ab6-822b2659ab8d"), Nombre = "ZACAPOAXTLA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("3ed9db02-4d2b-46bf-b3c3-da83d66155ae"), Nombre = "ZACATLAN" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("dfc41548-b8a7-406b-8a60-18cf4cdd4694"), Nombre = "ZARAGOZA" });
            modelBuilder.Entity<Municipio>().HasData(new Municipio { Id = new Guid("61727aec-a763-4485-8c77-488853676a1d"), Nombre = "ZOQUITLAN" });

            //Tipos de Inmuebles

            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("ea0787ab-3057-4201-b47e-69a5189a761b"), Nombre = "UNIDAD DE INVESTIGACION ACAJETE", Municipio = "ACAJETE", Direccion = "CALLE 2 ORIENTE ENTRE CALLE 8 NORTE Y CALLE 10 ORIENTE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("54d12595-7a9e-4592-8c0b-99da2932fcd5"), Nombre = "UNIDAD DE INVESTIGACION ACATENO", Municipio = "ACATENO", Direccion = "CALLE ALLENDE NO. 1 COL. CENTRO SAN JOSÉ ACATENO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("997a62a8-bd78-4381-a255-d9a8c3832e41"), Nombre = "CENTRO DE JUSTICIA PARA LAS MUJERES EN ACATLAN DE OSORIO", Municipio = "ACATLAN DE OSORIO", Direccion = "AV. REFORMA 22 COLONIA CENTRO ENTRE EMILIANO ZAPATA Y VENUSTIANO C" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("0fa248d3-69f1-4298-bb11-81e6b18a398e"), Nombre = "CASA DE JUSTICIA ACATLAN DE OSORIO", Municipio = "ACATLAN DE OSORIO", Direccion = "CARRETERA INTERNACIONAL MEXICO -OAXACA KM152+200, BARRIO LA PALMA , ACATLAN DE OSORIO PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("6f3a6d73-cab8-47dd-9d84-f7df07de7df3"), Nombre = "CENTRO INTEGRAL SERVICIOS ACATLÁN DE OSORIO ", Municipio = "ACATLAN DE OSORIO", Direccion = "CARRETERA FEDERAL NO.19, ACATLÁN DE OSORIO, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("9da88dc2-6616-4163-930d-fe1faca21657"), Nombre = "SEMEFO ACATLAN DE OSORIO ", Municipio = "ACATLAN DE OSORIO", Direccion = "CARRETERA INTERNACIONAL, BARRIO LA PALMA ACATLAN DE OSORIO  " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("75b487fb-b434-49c7-abc7-77250606a1a4"), Nombre = "UNIDAD DE INVESTIGACION ACATZINGO", Municipio = "ACATZINGO", Direccion = "AV. IGNACIO ROMERO VARGAS 201 COL CENTRO CP 75150" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("12ff0d33-065d-4d31-842a-91811242674b"), Nombre = "UNIDAD DE INVESTIGACIÓN AHUAZOTEPEC ", Municipio = "AHUAZOTEPEC", Direccion = "CALLE HIDALGO SUR  S/N COL. CENTRO (DENTRO DE LA PRESIDENCIA MUNICIPAL " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("4179b35b-018d-4fc2-847a-97aad0a386ea"), Nombre = "CENTRO INTEGRAL SERVICIOS  AJALPAN ", Municipio = "AJALPAN", Direccion = "CARRETERA ESTATAL 690 S/N , AJALPAN , PUEBLA, CP.: 75910" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("7fea22c0-e0a7-4fc2-ad47-d081064dffdc"), Nombre = "UNIDAD DE INVESTIGACION AJALPAN", Municipio = "AJALPAN", Direccion = "CALLE GUERRERO SIN NÚMERO, AJALPAN PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("8bebb72d-afc0-47a9-bfcb-bbc4135c1af2"), Nombre = "ARCO DE SEGURIDAD DE ALTEPEXI ", Municipio = "ALTEPEXI", Direccion = "CARRETERA ESTATAL TEHUACAN TEOTITLÁN OAXACA, TRAMO DE CHILACALTEPEXI,CP.: 75914" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("a2b4a20c-3c46-437a-a2ac-9c876acacc7e"), Nombre = "UNIDAD DE INVESTIGACION AMOZOC", Municipio = "AMOZOC", Direccion = "CALLE FRANCISCO I. MADERO 109 COLONIA CENTRO BARRIO DE SANTIAGO, AMOZOC, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("8a363d39-c4da-430d-8848-42bf513866eb"), Nombre = "ARCHIVO Y BODEGA DE INDICIOS", Municipio = "AMOZOC", Direccion = "KM 19.5 CARRETERA FEDERAL PUEBLA - TEHUACAN, COLONIA SAN JOSE LAS FLORES, CP 72980, AMOZOC" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("aac51f16-f316-44ac-a2fa-473f5f82199d"), Nombre = "UNIDAD DE INVESTIGACION ATEMPAN ", Municipio = "ATEMPAN", Direccion = "02 ORIENTE SIN NUMERO, COLONIA CENTRO, ATEMPAN, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("5398b61c-1577-4c36-a68f-085460f97b08"), Nombre = "UNIDAD DE INVESTIGACION ATENCINGO", Municipio = "ATENCINGO", Direccion = "CALLE 5 DE FEBRERO ESQUINA MIGUEL HIDALGO COL LA CRUZ" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("76e1e97d-1ce0-4335-ac9e-981aeb1562fa"), Nombre = "ARCO DE SEGURIDAD DE ATLÍXCO ", Municipio = "ATLIXCO", Direccion = "AUTOPISTA SIGLO XXI, KM 15+600 ATLIXCO,PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("16c18dc8-dbaf-4b0c-b8df-9dd6bbb4385b"), Nombre = "CASA DE JUSTICIA ATLIXCO ", Municipio = "ATLIXCO", Direccion = "BOULEVARD GENERAL MORENO VALLE NO. 1604, COL. TIZAYUCA ,ATLIXCO PUE. CP.: 74200" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f6f5ec29-7b21-462a-90b7-7c6b6d617a59"), Nombre = "CENTRO INTEGRAL SERVICIOS  ATLIXCO ", Municipio = "ATLIXCO", Direccion = "REVOLUCIÓN NO. 6202, COL. EL LEÓN ATLIXCO PUE, CP.: 74360" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("efe8487c-1068-4e19-aad1-6c0f2c4d168c"), Nombre = "SEMEFO ATLIXCO", Municipio = "ATLIXCO ", Direccion = "CALLE 5 PONIENTE 113, COL. CENTRO ATLIXCO " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("e484e377-cc09-4098-b595-2966661b1cac"), Nombre = "UNIDAD DE INVESTIGACION CALPAN", Municipio = "CALPAN", Direccion = "CALLE CONSTITUCION S/N ENTRE 16 DE SEPTIEMBRE Y DOMINGO ARENAS, PRESIDENCIA MUNICIPAL CALPAN, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("df565b02-4f00-4d24-9c6b-c935edc2b0bb"), Nombre = "CASA DE JUSTICIA CHALCHICOMULA DE SESMA ", Municipio = "CHALCHICOMULA DE SESMA", Direccion = "KM.28+285 CARRETERA FEDERAL EL SECO ASUMBULLA, CD. SERDAN, PUEBLA CP.: 75520" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("5862a80d-c5ec-4389-867b-ec4bc60e9abc"), Nombre = "CENTRO INTEGRAL DE SERVICIOS  CHALCHICOMULA DE SESMA ", Municipio = "CHALCHICOMULA DE SESMA", Direccion = "CARRETERA FEDERAL SERDÁN EL SECO KILOMETRO 28, CD. SERDAN PUEBLA CP.: 75520" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f350b9c0-947e-4428-a96f-589563bd3d5f"), Nombre = "SEMEFO CIUDAD SERDAN ", Municipio = "CHALCHICOMULA DE SESMA", Direccion = "CALLE 5 PONIENTE SIN NUMERO, C.D. SERDAN, CHALCHICOMULA DE SESMA " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("73132bd8-3ce8-4b7a-a6c8-beed00da244a"), Nombre = "ANTENA TETELES , EL PAPAYO Y REPETIDOR SAN BERNARDINA CHALCHIHUAPAN ", Municipio = "CHALCHIHUAPAN", Direccion = "CERRO EL PAPAGAYO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("bcfb55fe-413a-4c8d-8990-f6bd1594db5d"), Nombre = "UNIDAD DE INVESTIGACION CHIAUTLA DE TAPIA", Municipio = "CHIAUTLA DE TAPIA", Direccion = "CALLE REFORMA Y 5 NORTE COLONIA CENTRO, CHIAUTLA DE TAPIA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f04b392b-601f-4c73-b60e-6b95c37b4176"), Nombre = "UNIDAD DE INVESTIGACION CHIETLA", Municipio = "CHIETLA", Direccion = "CALLE RAYON NUMERO 4 COL. CENTRO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("7d977d82-0622-4415-adfa-168f4a78dffd"), Nombre = "SEMEFO CHIGNAHUAPAN", Municipio = "CHIGNAHUAPAN", Direccion = "BOULEVARD EMILIANO ZAPATA SIN NUMERO, INTERIOR DEL PANTEON MUNICIPAL, CHIGNAHUAPAN,PUEBLA " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f47edbb8-650f-4756-a5f3-fbf4d62c1261"), Nombre = "UNIDAD DE INVESTIGACION CHIGNAHUAPAN", Municipio = "CHIGNAHUAPAN", Direccion = "LIBRAMIENTOCHIGNAHUAPAN - ZACATLAN, KM 4.5 BARRIO TOLTEMPAN, CHIGNAHUAPAN, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("47c5a6a5-ebca-460c-a931-b446bc4ae13a"), Nombre = "UNIDAD DE INVESTIGACION  CORONANGO", Municipio = "CORONANGO", Direccion = "AV. 5 DE FEBRERO NORTE SIN NUMERO COL. EL MONTERO CORONANGO, PUEBLA  COMPLEJO METROPOLITANO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("0dbd6fd2-8c56-4562-8e21-dd018b174ee1"), Nombre = "COMPLEJO METROPOLITANO SEGURIDAD PÚBLICA  (C5) ", Municipio = "CUAUTLANCINGO", Direccion = "PERIFERICO ECOLÓGICO KILÓMETRO 3.5 ANTIGUO CAMINO A SAN FRANCISCO OCOTLÁN,CUAUTLANCINGO PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("66451a35-3553-401e-a2c3-d02d5d80a805"), Nombre = "UNIDAD DE INVESTIGACION CUAUTLANCINGO", Municipio = "CUAUTLANCINGO", Direccion = "CALLE CAMINO NACIONAL ESQUINA CON AQUILES SERDAN SIN NUMERO, COLONIA BELLO HORIZONTE, CUAUTLANCINGO  COMPLEJO DE SEGURIDAD" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("02794a34-a930-4f9b-bfed-0294a49b7288"), Nombre = "CENTRO INTEGRAL DE SERVICIOS CUAUTLANCINGO", Municipio = "CUAUTLANCINGO", Direccion = "CALLE AQUILES SERDAN ESQUINA CON 20 DE NOVIEMBRE SIN NUMERO, COLONIA BELLO HORIZONTE, CUAUTLANCINGO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("a997fc37-85dd-4508-9a5e-76f1a64d8ccc"), Nombre = " UNIDAD DE INVESTIGACIÓN VW", Municipio = "CUAUTLANCINGO", Direccion = "AV. SAN LORENZO ALMECATLA SIN NUMERO PLAZA MOVAR SANCTORUM" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("8c0c4bc9-bbad-44d6-8fde-76be64c12cb8"), Nombre = "DEPOSITO DE VEHICULOS CUAUTLANCINGO (CAPULIN)", Municipio = "CUAUTLANCINGO", Direccion = "CARRETERA A TLAXCALA KM 10 CUAUTLANCINGO, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("c79300f4-0dfc-46da-ba2b-63c882bc80cb"), Nombre = "UNIDAD DE INVESTIGACION CUETZALÁN DEL PROGRESO ", Municipio = "CUETZALAN DEL PROGRESO", Direccion = "CALLE MIGUEL ALVARADO ESQUINA CON ABASOLO S/N COLONIA CENTRO C.P. 75040 CUETZALAN PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("d2aba852-a956-4625-8b91-46594f19e8ae"), Nombre = "UNIDAD DE INVESTIGACION ESPERANZA", Municipio = "ESPERANZA", Direccion = "CALLE 12 NORTE SEGUNDA SECCION 22, ESPERANZA, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("db79d375-08c0-402c-9891-a1e1ea6e47b4"), Nombre = "UNIDAD DE INVESTIGACION Y MEDIOS ALTERNATIVOS", Municipio = "GUADALUPE VICTORIA", Direccion = "AV. 5 DE MAYO NO.1 EXTERIOR DE LA PRESIDENCIA MUNICIPAL, GUADALUPE VICTORIA , PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("21ece737-52f7-4b09-bcae-69005426a9cd"), Nombre = "CASA DE JUSTICIA HUAUCHINANGO ", Municipio = "HUAUCHINANGO", Direccion = "CAMINO A CATALINA S/N COLONIA EL POTRO, HUAUCHINANGO, PUEBLA CP.: 73176" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("34171fa2-4d08-47d9-907b-d8e9f74ea9a9"), Nombre = "SEMEFO HUAUCHINANGO", Municipio = "HUAUCHINANGO", Direccion = "CALLE TIRZO TELLEZ SIN NUMERO COL. EL CRISTO, HUAUCCHINANGO, PUEBLA " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("dd381283-4c21-484b-91e2-305c7803c22d"), Nombre = "UNIDAD DE INVESTIGACION HUEHUETLA ", Municipio = "HUEHUETLA", Direccion = "CALLE JUAREZ SUR S/N COL. YALU LOCALUDAD PUTAX-EAT, HUEHUETLA, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("418b2be0-cd91-4bad-b9f4-c6f65dc2119d"), Nombre = "SEMEFO HUEJOTZINGO TERRENO", Municipio = "HUEJOTZINGO", Direccion = "JUNTA AUXULIAR SANTA ANA XALMIMILULCO, ANTIGUA FINCA DE SANTA ANA DE ABAJO PREDIO 5" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("ab889720-0f37-4d94-a903-741bfc3ff9fb"), Nombre = "ARCO DE SEGURIDAD HUEJOTZINGO ", Municipio = "HUEJOTZINGO", Direccion = "CARRETERA MÉXICO -PUEBLA KM100+200 HUEJOTZINGO ,PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("1c8e7a04-f572-402e-af53-175d13989394"), Nombre = "UNIDAD DE INVESTIGACION  ADSCRITA A JUZGADOS PENALES Y CIVILES ", Municipio = "HUEJOTZINGO", Direccion = "AV DE LAS HUERTAS 917 CUARTO BARRIO COL. CENTRO, HUEJOTZINGO, PUEBLA, CP.: 74168" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("8eeef5ac-4c1e-4a29-b573-3a43771ff75d"), Nombre = "AGENCIA ESTATAL DE INVESTIGACIÓN", Municipio = "HUEJOTZINGO", Direccion = "BLVD. 18 DE MARZO NUMERO 52 COLONIA EL PARAISO, HUEJOTZINGO, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("49c6c10e-90c6-43fd-86f2-bd7365a08f57"), Nombre = "UNIDAD DE INVESTIGACION HUEYTAMALCO ", Municipio = "HUEYTAMALCO", Direccion = "CALLE INDEPENDENCIA ESQ. CON CALLE 5 DE MAYO S/N COL. CENTRO, HUEYTAMALCO, PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("5c6b1182-7c0e-4567-9cdf-0a2d20b09fe5"), Nombre = "UNIDAD DE INVESTIGACION CRIMINAL Y UNIDAD DE ATENCIÓN TEMPRANA  IZUCAR DE MATAMOROS ", Municipio = "IZUCAR DE MATAMOROS", Direccion = "PRIVADA UNIVERSIDAD II SAN MARTIN ALCHICHICA, IZUCAR DE MATAMOROS,PUEBLA " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("18af5009-c71b-4ef5-aba2-0e47881a77ca"), Nombre = "ARCO DE SEGURIDAD DE IZÚCAR DE MATAMOROS ", Municipio = "IZUCAR DE MATAMOROS", Direccion = "CARRETERA FEDERAL IZÚCAR DE MATAMOROS KM61+800 IZUCAR DE MATAMOROS" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("a4620e16-43bb-4478-a846-8b14f2a87d9a"), Nombre = "CASA DE JUSTICIA IZÚCAR DE MATAMOROS", Municipio = "IZUCAR DE MATAMOROS", Direccion = "CARRETERA FEDERAL PUEBLA-IZUCAR DE MATAMOROS NO. 2119, COL. GALARZA, IZUCAR DE MATAMOROS, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("dfaeed5a-c80f-4191-9fcf-01d4b4a753db"), Nombre = "CENTRO INTEGRAL SERVICIOS  IZUCAR DE MATAMOROS ", Municipio = "IZUCAR DE MATAMOROS", Direccion = "INTERNACIONAL A OAXACA 2,BARRIO DE SAN JUAN PIAXTLA IZUCAR DE MATAMOROS ,PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("379b9188-cb1e-46e7-a4c7-3faa87163b45"), Nombre = "SEMEFO IZUCAR DE MATAMOROS ", Municipio = "IZUCAR DE MATAMOROS", Direccion = "  PANTEON MUNICIPAL, BARRIO DE SANTA CRUZ, TEXCOCO, CALLE REVOLUCION Y HERCULANO SANCHEZ " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("9e54398a-156c-4d59-a439-8dc24d54e427"), Nombre = "UNIDAD DE INVESTIGACION JUAN C BONILLA", Municipio = "JUAN C. BONILLA", Direccion = "CALLE 5 DE MAYO S/N COLONIA CENTRO, JUAN C. BONILLA, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("633519e6-ead6-4b81-8034-cc407301a215"), Nombre = "UNIDAD DE INVESTIGACION LIBRES", Municipio = "LIBRES", Direccion = "CALLE LERDO NUMERO 988, LIBRES, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("ae00d1a5-1d40-41d2-8a08-5755abddbdbf"), Nombre = "SEMEFO LIBRES", Municipio = "LIBRES", Direccion = "CALLE 4 ORIENTE SIN NUMERO BARRIO DE GUADALUPE " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("0a0322cb-1b9c-4702-9df4-9fdf87b39bf0"), Nombre = "CASA DE JUSTICIA LIBRES", Municipio = "LIBRES ", Direccion = "CALLE LERDO NUMERO 988, LOS CONOS LIBRES, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("88754927-6c86-414a-b1a7-1d9a50a45d54"), Nombre = "UNIDAD DE INVESTIGACION LOS REYES DE JUAREZ", Municipio = "LOS REYES DE JUAREZ", Direccion = "AVENIDA MERINO FERNANDEZ ENTRE CALLE JUAREZ Y CALLE AYUNTAMIENTO, PRESIDENCIA MUNCIAL, COL. CENTRO, LOS REYES DE JUAREZ, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("5fabc11c-cb4e-4120-805d-4334f47d233c"), Nombre = "UNIDAD DE INVESTIGACION METLATOYUCA ", Municipio = "METLALTOYUCA", Direccion = "AVENIDA REYES GARCIA 57 COLONIA ERMITA, METLALTOYUCA, PUEBLA. CP 73000" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("6d1c2e9c-5fe4-45ba-9da7-29f76bac1841"), Nombre = "UNIDAD DE INVESTIGACION OCOYUCAN", Municipio = "OCOYUCAN", Direccion = "PLAZA PRINCIPAL S/N PLANTA BAJA, PALACIO MUNICIPAL, COL. CENTRO, SANTA CLARA OCOYUCAN" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("9f24386a-81ef-4601-bc4f-2b0ee4b96639"), Nombre = "SEMEFO ORIENTAL", Municipio = "ORIENTAL", Direccion = "CAMINO AL PANTEON SIN NUMERO COLONIA CENTRO, ORIENTAL, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("604009aa-027e-490a-b552-9c76101b6d8a"), Nombre = "UNIDAD DE INVESTIGACION ORIENTAL", Municipio = "ORIENTAL", Direccion = "AV. AYUNTAMIENTO NO. 3 COL. CENTRO CP 75020" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("97312b95-bae0-4624-a208-a8f73533c216"), Nombre = "ARCO DE SEGURIDAD PALMAR DE BRAVO ", Municipio = "PALMAR DE BRAVO", Direccion = "CARRETERA MÉXICO VERACRUZ KM 166+500PALMAR DE BRAVO , PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("aab687d1-1489-46b4-91ef-5a04e387d9ef"), Nombre = "UNIDAD DE INVESTIGACION PALMAR DE BRAVO ", Municipio = "PALMAR DE BRAVO", Direccion = "CALLE NICOLAS BRAVO #504 COL. CENTRO PLAMAR DE BRAVO " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("c3a22f92-ab1f-4078-9bf9-c8e0e05f1345"), Nombre = "UNIDAD DE INVESTIGACION PIAXTLA", Municipio = "PIAXTLA", Direccion = "PLAZA EXPLANADA PALACIO MUNICIPAL S/N COL. CENTRO PRIMER PISO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f70ae993-4797-4608-95dc-b931e68f5ccc"), Nombre = "EDIFICIO CENTRAL 04", Municipio = "PUEBLA", Direccion = "BOULEVARD HEROES 5 DE MAYO ESQUINA CON 31 ORIENTE COL.LADRILLERA DE BENITEZ CP.: 72530" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f6ea5fc3-c586-47ea-957d-9320b9464dd5"), Nombre = "CENTRO DE JUSTICIA PARA LAS MUJERES PUEBLA ", Municipio = "PUEBLA", Direccion = "CALLE 17 PONIENTE NO.1919, BARRIO DE SANTIAGO,PUEBLA, PUE. CP.: 72410" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("1cb1ac85-d878-42db-9ef8-ec848407ebdf"), Nombre = "FISCALÍA ESPECIALIZADA EN INVESTIGACIÓN DE DELITOS DE VIOLENCIA DE GÉNERO CONTRA LAS MUJERES (CPJ)", Municipio = "PUEBLA", Direccion = "CALLE 10 ORIENTE NO.414,COL CENTRO PUEBLA,PUE. CP.: 72530" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("05f794c3-f900-4941-a15e-cca8664ac6e1"), Nombre = "INDIGENAS PERIODISTAS LGBTTQ", Municipio = "PUEBLA", Direccion = "PRIV. 5 B SUR NO. 3706, COL. GABRIEL PASTOR, PUEBLA, PUE CP. 72420" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("50ff685d-2657-4042-8319-c3c6d7fa505e"), Nombre = "FISCALIA DE DERECHOS HUMANOS", Municipio = "PUEBLA", Direccion = "CALLE 12 ORIENTE NO. 415 COL. CENTRO, PUEBLA, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("3d261dbb-2a81-491a-af78-659331b86c4a"), Nombre = "FISCALÍA ESPECIALIZADA EN INVESTIGACIÓN DE DELITOS DE VIOLENCIA DE GÉNERO CONTRA LAS MUJERES (BOCHAS)", Municipio = "PUEBLA", Direccion = "CALLE 6 NORTE NO.1003, COL. CENTRO,PUEBLA PUE. CP.: 72000" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("e11c2009-ce5f-4adb-aa33-c882aeff8449"), Nombre = "FISCALIA ESPECIALIZADA EN INVESTIGACION DE DELITOS DE ALTA INCIDENCIA", Municipio = "PUEBLA", Direccion = "CALLE 127 PONIENTE Y CALLE 11 SUR , COL.EX-HACIENDA CASTILLOTLA, PUEBLA,PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("75f66bef-947b-4731-a7c8-e6897cd0d31c"), Nombre = "INMUEBLE DE LA 16 ORIENTE ", Municipio = "PUEBLA", Direccion = "AV. MIGUEL HIDALGO NO. 16,COL. EL PORVENIR ,PUEBLA,PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("5c49c4fa-1770-4c96-adbb-c95540a0c85d"), Nombre = "INSTITUTO DE FORMACIÓN PROFESIONAL   ", Municipio = "PUEBLA", Direccion = "DIAGONAL CUAUHTÉMOC NO.3101 COL. VALLE DORADO PUEBLA,PUE. CP.: 72070" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("7c90783c-73d4-4435-97f0-1255181a81ac"), Nombre = "COORDINACIÓN GENERAL DE MECANISMOS ALTERNATIVOS DE SOLUCION DE CONTROVERSIAS EN MATERIA PENAL", Municipio = "PUEBLA", Direccion = "DIAGONAL DEFENSORES DE LA REPÚBLICA ESQ.10 PONIENTE COL.AMOR PUEBLA,PUE. CP.: 72140" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("5e3c77e9-74e5-4a6e-ad3d-de540745e37f"), Nombre = "FISCALIA DE ASUNTOS INTERNOS, ORGANO INTERNO DE CONTROL Y VISITADURIA ", Municipio = "PUEBLA", Direccion = "12 NORTE. NO.1806,COL. BARRIO DEL ALTO , PUEBLA PUE. CP.: 72146" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f586dc78-1395-493e-87f7-16d41d377301"), Nombre = "UNIDAD DE IDENTIFICACIÓN VEHICULAR ", Municipio = "PUEBLA", Direccion = "EMILIANO ZAPATA KM2.5,COL LOMAS DE SAN MIGUEL,PUEBLA,PUE. CP.: 72573" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("9e238566-245c-44ba-a61c-8a4f7bb7f7d8"), Nombre = "UNIDAD ESPECIALIZADA DE INVESTIGACIÓN DE ROBO DE VEHICULOS (OCRA)", Municipio = "PUEBLA", Direccion = "CAMINO AL BATÁN KM2.5 COL.LOMAS DE SAN MIGUEL PUEBLA,PUE. CP.: 72573" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("c1ee4f7d-93dd-4d48-be9d-1324a40e4fc2"), Nombre = "DEPOSITO DE VEHÍCULOS OCRA - SAN MIGUEL 2", Municipio = "PUEBLA", Direccion = "CAMINO AL BATÁN COL.LOMAS DE SAN MIGUEL PUEBLA,PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("7a465d4d-7292-4a37-a4fb-0d1a554573e5"), Nombre = "CENTRO INTEGRAL DE SERVICIOS  SAN JAVIER ", Municipio = "PUEBLA", Direccion = "AV. REFORMA 1305 COL CENTRO C.P. 72000" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("9ea85a40-40a0-441c-9cc4-0c37d28aea28"), Nombre = "CENTRO INTEGRAL DE SERVICIOS ANGELÓPOLIS ", Municipio = "PUEBLA", Direccion = "VÍA ATLIXCAYOTL NO. 1101, EDIFICIO SUR PLANTA BAJA , CONCEPCION LAS LAJAS , PUEBLA,PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("35f7fae6-21b0-438c-966b-17442bacdf89"), Nombre = "EJECUCION DE SENTENCIAS ", Municipio = "PUEBLA", Direccion = "KM 2.5 CARRETERA AL BATAN , EDIFICIO ADJUNTO AL CERESO DE SAN MIGUEL PUEBLA,PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("58f8f4bf-66c5-48da-a474-d360097bcb73"), Nombre = "UNIDAD DE INVESTIGACION LA POPULAR", Municipio = "PUEBLA", Direccion = "AV.105 PONIENTE ENTRE CALLE PUEBLA Y OAXACA COL.POPULAR CASTILLOTLA, PUEBLA," });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("360e0d81-dff5-4de9-b354-1e4da4f14165"), Nombre = "UNIDAD DE INVESTIGACION ORIENTE", Municipio = "PUEBLA", Direccion = "PROLONGACIÓN 16 ORIENTE ESQ. CON LIBRAMIENTO A TEHUACAN COL. MEXICO 68" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("e8923eed-5915-4543-9ce6-dbdfbc31c67a"), Nombre = "UNIDAD DE INVESTIGACION VIRTUAL PREDENUNCIA EL CARMEN ", Municipio = "PUEBLA", Direccion = "CALLE 21 ORIENTE NO.404, COL. EL CARMEN, PUEBLA,PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("6d545b8c-a620-4871-86ef-528430c61e1e"), Nombre = "UNIDAD DE INVESTIGACIÓN CENTRO", Municipio = "PUEBLA", Direccion = "9 ORIENTE NO.1405COL.CENTRO PUEBLA PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("a63b7be7-32d5-4958-8254-1162c906ddd7"), Nombre = "UNIDAD DE INVESTIGACIÓN VALSEQUILLO", Municipio = "PUEBLA", Direccion = "BOULEVARD VALSEQUILLO ESQU. 20 DE NOVIEMBRE COL. SAN BALTAZAR CAMPECHE, PUEBLA,PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f470ce98-458d-4a21-856d-846424d5aefc"), Nombre = "UNIDAD ESPECIALIZADA ADSRCITA A LA FISCALIA METROPOLITANA (JUZGADOS PENALES)   ", Municipio = "PUEBLA", Direccion = "CALLE 12 ORIENTE NO. 608 COL. CENTRO ,PUEBLA, PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("43329601-aaf1-4505-a114-c5e2c0404ca6"), Nombre = "INMUEBLE CANACINTRA", Municipio = "PUEBLA", Direccion = "AV. REFORMA 2704 5° PISO COL. AMOR" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("2d8aa1ef-75b9-4ca5-9d34-ff910f146677"), Nombre = "ESTADIO ZARAGOZA", Municipio = "PUEBLA", Direccion = "CALLE AL ESTADIO ZARAGOZA, BARRIO DE XANENETLA, PLANTA BAJA Y PRIMER NIVEL, ESTADIO ZARAGOZA, 72000, PUEBLA, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("42ae640d-789f-4262-bc0f-9fdc6ef3c504"), Nombre = "JUSTICIA CIUDADANA", Municipio = "PUEBLA", Direccion = "13 SUR 1910 BARRIO DE SANTIAGO PUEBLA PUE" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("4accb2ff-b226-47ac-bfad-9055220fc68b"), Nombre = "UNIDAD DE INVESTIGACIÓN VILLA FRONTERA", Municipio = "PUEBLA", Direccion = "CALLE FRANCISCO I. MADERO NO. 07 COL. CENTRO, SAN PABLO XOCHIMEHUACAN" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("542c1a9a-46db-451a-a395-e7ef22925811"), Nombre = "DEPOSITO DE VEHICULOS SANCTORUM (FINSA)", Municipio = "PUEBLA", Direccion = "RIO ATOYAC # 19 SANCTORUM" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("79302577-eff3-4087-93db-599dc70f3c13"), Nombre = " UNIDAD DE INVESTIGACIÓN LA MARGARITA", Municipio = "PUEBLA", Direccion = "CAMINO AL BATAN NO. 12 COL. VILLA SATELITE LA CALERA PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("a70575f3-3ffb-4d12-af9c-8dc3b641fcbd"), Nombre = "ALMACEN GENERAL", Municipio = "PUEBLA", Direccion = "CALLE ORQUIDEAS NO. 6141 COLONIA BUGAMBILIAS CP 72580" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("b06290e8-8fcc-430e-abec-1399c33c520c"), Nombre = "UNIDAD DE INVESTIGACION CHAPULCO", Municipio = "PUEBLA", Direccion = "PROLONGACION DE LA 14 SUR NUMERO 11517 COL. SAN JOSE CHAPULCO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("2105684c-46b6-41c5-bd73-024885f82f3e"), Nombre = "SEMEFO 11 SUR ", Municipio = "PUEBLA ", Direccion = "PROLONGACION 11 SUR 11906, COL. GUADALUPE HIDQLGO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("02063a14-db5e-4cb5-a163-f4e3ecbf84b3"), Nombre = "UNIDAD INTEGRAL DE SERVICIOS EL ALTO ", Municipio = "PUEBLA ", Direccion = "CALLE 8 ORIENTE, NUMERO 1007, COLONIA SAN FRANCISCO, PUEBLA, PUE. " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("3e885b08-c87a-457a-9b57-6939a4034323"), Nombre = "AGENCIA ESTATAL DE INVESTIGACION ", Municipio = "PUEBLA ", Direccion = "AV. 25 ORIENTE  #1610 BELLA VISTA, PUEBLA, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("a1a9e843-9a4e-49eb-b6be-d70511e89a75"), Nombre = "FISCALIA ESPECIALIZADA DE COMBATE A LA CORRUPCION, FISCALIA ESPECIALIZADA EN INVESTIGACION DE LOS DELITOS DE DESAPARICION FORZADA DE PERSONAS Y DESAPARICION COMETIDA POR PARTICUALRES", Municipio = "PUEBLA", Direccion = "AVENIDA 16 DE SEPTIEMBRE NUMERO 2904 COLONIA EL CARMEN, PUEBLA, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("af99061f-36ab-46f4-97f5-618dad2a5cae"), Nombre = "FISCALÍA ESPECIALIZADA EN INVESTIGACIÓN DE SECUESTRO Y EXTORSIÓN", Municipio = "SAN ANDRES CHOLULA", Direccion = "3ER RETORNO OSA MENOR NO.3, RESERVA TERRITORIAL ATLIXCAYOTL ,SAN ANDRÉS" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("1c2468eb-8298-4bb5-a775-951ec6779458"), Nombre = "COORDINACION GENERAL DE ANALISIS DE INFORMACION ", Municipio = "SAN ANDRES CHOLULA", Direccion = "TERCER RETORNO OSA MAYOR NO. 3, RESERVA TERRITORIAL ATLIXCAYOTL SAN ANDRES" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("2071ce79-2ad0-4f8c-b7ce-c979aeb07829"), Nombre = "CASA DE JUSTICIA PARA ADOLESCENTES", Municipio = "SAN ANDRES CHOLULA", Direccion = "CARRETERA IZUCAR DE MATAMOROS S/N COL. TLAXCALANCINGO, CP.: 72820" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("d1e510c1-98dd-49b6-a4a9-4d15658d5e12"), Nombre = "CASA DE JUSTICIA SAN ANDRES CHOLULA ", Municipio = "SAN ANDRES CHOLULA", Direccion = "PERIFÉRICO ECOLÓGICO 100 SAN BERNARDINO TLAXCALANCINGO SAN ANDRES CHOLULA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("ebcbb7fe-22b1-4fdc-8ab9-e1743671cf55"), Nombre = "CENTRO INTEGRAL SERVICIOS  SAN ANDRES CHOLULA ", Municipio = "SAN ANDRES CHOLULA", Direccion = "ANILLO PERIFERICO ECOLOGICO SIN NUEMERO COL. EMILIANO ZAPATA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("3010e2c0-ae15-4d01-af42-eb075c067a59"), Nombre = "COMPLEJO DE SEGURIDAD PÚBLICA SAN ANDRES CHOLULA ", Municipio = "SAN ANDRES CHOLULA", Direccion = "CAMINO A CUAYANTLA NO. 1611, SAN BERNARDINO TLAXCALANCINGO, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("ea76efef-50bb-4c85-aa43-a834a5db3f7f"), Nombre = "UNIDAD DE INVESTIGACION CIUDAD JUDICIAL ", Municipio = "SAN ANDRES CHOLULA", Direccion = "PERIFERICO ECOLOGÍCO ARCO SUR NO. 4000, RESERVA TERRITORIAL ATLIXCAYOTL, SAN" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("e1a8b510-6500-4a29-a904-de39e59c7062"), Nombre = "UNIDAD DE INVESTIGACION SAN GABRIEL CHILAC", Municipio = "SAN GABRIEL CHILAC", Direccion = "AVENIDA NIÑOS HEROES SIN NUMERO COLONIA EL SOL, SAN GABRIEL CHILAC, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("db4c1ada-9e03-4fd4-9887-cb1446d279c0"), Nombre = "CENTRO INTEGRAL SERVICIOS  SAN JOSE CHIAPA ", Municipio = "SAN JOSE CHIAPA", Direccion = "MANZANA NÚMERO 5 CIUDAD MODELO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("7cd298aa-a271-438a-928d-3cca6e936391"), Nombre = "CASA DE JUSTICIA SAN MARTÍN TEXMELUCAN ", Municipio = "SAN MARTIN TEXMELUCAN", Direccion = "AUTOPISTA MÉXICO -PUEBLA S/N, SAL SALVADOR EL VERDE, SAN MARTIN TEXMELUCAN," });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f1923ee5-86b3-48c5-984a-5feba4f02581"), Nombre = "AGENCIA ESTATAL DE INVESTIGACION SAN MARTIN TEXMELUCAN ", Municipio = "SAN MARTIN TEXMELUCAN", Direccion = "CALLE VICENTE GUERRERO NO.714 COL, MORELOS SAN MARTIN TEXMELUCAN, CP.: 74020" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("b06b8873-efca-4b44-8b9c-13a830d2abb3"), Nombre = "CANACO SAN MARTIN TEXMELUCAN", Municipio = "SAN MARTIN TEXMELUCAN", Direccion = "REFORMA 3 ORIENTE, COL. CENTRO 74000 SAN MARTIN TEXMELUCAN, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("b6c62d0f-ca04-4675-8a7b-9ebfac840a0c"), Nombre = "TERRENO SAN JOSE ACTIPAN CHOLULA", Municipio = "SAN PEDRO CHOLULA", Direccion = "CUARTA FRACCIÓN RANCHO DE SAN JOSE ACTIPAC, COL. SAN PEDRO MEXICALTZINGO," });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("613e2684-b49a-4cec-aa4a-a863833635d8"), Nombre = "ARCHIVO DISTRITAL", Municipio = "SAN PEDRO CHOLULA", Direccion = "CALLE HIDALGO NO. 701 COL. CENTRO, SAN PEDRO CHOLULA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("43eb3a2c-e1ea-45dd-8bc9-9082da8f5ab2"), Nombre = "UNIDAD DE INVESTIGACION SAN PEDRO CHOLULA", Municipio = "SAN PEDRO CHOLULA", Direccion = "CALLE 15 NORTE SIN NÚMERO, SEGUNDO PISO, SAN MATÍAS COCOYOTLA, SAN PEDRO CHOLULA, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("7a7898ea-b1c6-4927-b759-25d61ac7dd22"), Nombre = "UNIDAD DE INVESTIGACION EL SECO", Municipio = "SAN SALVADOR EL SECO", Direccion = "AV. 4 ORIENTE SIN NUMERO TECOAC" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("e3a432ab-30cd-4d11-b25d-63bc469f267d"), Nombre = "AGENCIA ESTATAL DE INVESTIGACION SANTA RITA TLAHUAPAN ", Municipio = "SANTA RITA TLAHUAPAN", Direccion = "CALLE JOSE GALEANA NO. 200 COLONIA DOMINGO ARENAS, SANTA RITA TLAHUAPAN" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("2263367d-0dd3-48b4-8a6b-801b20495c12"), Nombre = "UNIDAD DE INVESTIGACION SANTA RITA TLAHUAPAN", Municipio = "SANTA RITA TLAHUAPAN", Direccion = "CALLE MIGUEL HIDALGO S/N COL. CENTRO 74100, SANTA RITA TLAHUAPAN, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("ec0684fb-691e-4461-a5e1-00c14dac3b02"), Nombre = "UNIDAD DE INVESTIGACION SANTIAGO MIAHUATLAN", Municipio = "SANTIAGO MIAHUATLAN", Direccion = "11 PONIENTE ENTRE 1 SUR Y AV. NACIONAL, SANTIAGO MIAHUATLAN, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("517d2546-abfd-48aa-8bc7-33c1873886fc"), Nombre = "UNIDAD DE INVESTIGACION TECALI DE HERRERA ", Municipio = "TECALI DE HERRERA", Direccion = "CALLE DE HERRERA S/N COL. CENTRO, TECALI DE HERRERA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f3c5ed2b-980a-4590-ad5b-99677883bd1d"), Nombre = "AGENCIA ESTATAL DE INVESTIGACION", Municipio = "TECALI DE HERRERA", Direccion = "17 SUR NUMERO 304 COLONIA BARRIO DE ANALCO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("e7c913cc-ea42-473c-9693-03873430a89b"), Nombre = "CASA DE JUSTICIA TECAMACHALCO ", Municipio = "TECAMACHALCO", Direccion = "CARRETERA FEDERAL KM 60+490, COL.SANTIAGO ALSESECA, TECAMACHALCO, CP.: 75480" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("60468304-b094-46f8-9113-89bf24e222ed"), Nombre = "CENTRO INTEGRAL SERVICIOS  TECAMACHALCO ", Municipio = "TECAMACHALCO", Direccion = "CALLE 7 ORIENTE S/N COL. CENTRO, CP.: 75480" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("001890e1-494f-4bd0-8296-0844d17a52b2"), Nombre = "SEMEFO TECAMACHALCO ", Municipio = "TECAMACHALCO", Direccion = " A.V. GUERRERO ENTRE CALLE 31 SUR, Y CARRETERA A SAN MATEO TLAIXCAPAN" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("29d78cdf-7d81-4434-87a7-d8a096fb5262"), Nombre = "UNIDAD DE INVESTIGACION TECAMACHALCO", Municipio = "TECAMACHALCO", Direccion = "CALLE 10 SUR 507, BARRIO DE SAN JOSE, TECAMACHALCO, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("4f74a07c-dcc2-492f-b861-aa33f1c06f89"), Nombre = "CENTRO DE JUSTICIA PARA LAS MUJERES TEHUACÁN ", Municipio = "TEHUACAN", Direccion = "CALLE COMPLUTENSE ESQUINA CALLE DE LA TURBINA S/N COL. UNIVERSIDADES II, TEHUACAN ,PUE. CP.: 75723" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("86c1dc53-9781-4c00-9e35-435434182bb5"), Nombre = "ARCO DE SEGURIDAD DE CUAPIAXTLA DE MADERO ", Municipio = "TEHUACAN", Direccion = "CARRETERA FEDERAL A TEHUACÁN KM 43+800" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("551d631a-1bf3-4c74-8d31-339b2cf1b06e"), Nombre = "CASA DE JUSTICIA TEHUACÁN ", Municipio = "TEHUACAN", Direccion = "BLVD. ADOLFO MATEOS NO.4, PLANTA ALTA, COL. ZONA ALTA, TEHUACAN, PUEBLA CP.: 75750" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("3c68d977-b39e-42ba-8cdb-32b755568792"), Nombre = "CENTRO INTEGRAL SERVICIOS TEHUACAN ", Municipio = "TEHUACAN", Direccion = "CARRETERA FEDERAL PUEBLA - TEHUACÁN KILOMETRO 114, MANANTIALES, TEHUACÁN, PUE. CP.: 75855" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("dae3d229-4207-429c-9e57-f8cccc6ee315"), Nombre = "C5 TEHUACAN", Municipio = "TEHUACAN", Direccion = "CARRETERA FEDERAL PUEBLA TEHUACAN 1211 O KM 114 SAN LORENZO TEOTIPILCO, TEHUACAN, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("a39ac9f9-c924-45b9-b1be-267666325a32"), Nombre = "INSTITUTO DE CIENCIAS FORENSES TEHUACAN ", Municipio = "TEHUACAN", Direccion = "CALZADA ADOLFO LÓPEZ MATEOS NO.3210 LOCAL 21A, COL.ZONA ALTA TEHUACAN, PUEBLA, CP.: 75750" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("7312e9c9-0580-405e-a888-5143fe0dd037"), Nombre = "SEMEFO TEHUACAN ", Municipio = "TEHUACAN ", Direccion = "CALLE 19 PONIENTE SIN NUMERO PANTEON MUNICIPAL, TEHUACAN PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("a1908d9e-faa2-4a56-9f11-2dea75caa8d8"), Nombre = "UNIDAD DE INVESTIGACION TEHUITZINGO", Municipio = "TEHUITZINGO", Direccion = "CALLE LA PRESA SECCIÓN TERCERA, TEHUITZINGO , PUEBLA " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("eec8040b-0e53-4e24-943a-3918698d83f3"), Nombre = "UNIDAD DE INVESTIGACION TEPANCO", Municipio = "TEPANCO DE LOPEZ", Direccion = "PRIV. 8 PONIENTE S/N COL. CENTRO 75800, TEPANCO DE LOPEZ, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("639b4773-ad67-4cfe-9fae-4fdb68abcbe8"), Nombre = "UNIDAD DE INVESTIGACION TEPATLAXCO", Municipio = "TEPATLAXCO DE HIDALGO", Direccion = "2 SUR ESQUINA CON 9 ORIENTE S/N COL. CENTRO, TEPATLAXCO DE HIDALGO, PRIMER PISO" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("dc69dab8-8924-4f3b-baca-135fa879ead5"), Nombre = "UNIDAD DE INVESTIGACIÓN TEPEACA", Municipio = "TEPEACA", Direccion = "AVENIDA HIDALGO NÚMERO 509 A, TEPEACA PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("eefb8302-4983-458b-baa9-b524aebd8ee3"), Nombre = "SEMEFO TEPEACA ", Municipio = "TEPEACA ", Direccion = "INTERIOR DEL PANTEON MUNICIPAL, CALLE 17 ORIENTE Y AVENIDA COLON SIN NUMERO, BARRIO EL  SANTUARIO  " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("3e4a271f-71db-4e3b-a940-15376681ff4a"), Nombre = "UNIDAD DE INVESTIGACION TEPEOJUMA", Municipio = "TEPEOJUMA", Direccion = "CALLE IRINEO VAZQUEZ, NÚMERO 1, TEPEOJUMA, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("2102c0c8-e76f-49ad-a3dd-6c25cc19a08f"), Nombre = "CENTRO INTEGRAL SERVICIOS  TEPEXI DE RODRÍGUEZ ", Municipio = "TEPEXI DE RODRIGUEZ", Direccion = "CUAPIXTLA - ACATLÁN DE OSORIO NO. 35 SAN SEBASTIAN DE TEPEXI DE RODRIGUEZ , PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("95f5f5dc-acf5-4fc5-bb10-ccd0555f8d9f"), Nombre = "UNIDAD DE INVESTIGACION TEPEXI DE RODRÍGUEZ ", Municipio = "TEPEXI DE RODRIGUEZ", Direccion = "CALLE 5 DE FEBRERO PLAZA COMUNITARIA PROF .ABEL CRUZ GARCIA , NÚMERO 3  COL CENTRO, TEPEXI DE RODRIGUEZ PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("599ac965-a47e-4888-bc63-a300affb0a65"), Nombre = "SEMEFO TEPEXI DE RODRIGUEZ ", Municipio = "TEPEXI DE RODRIGUEZ", Direccion = "PANTEON MUNICIPAL CALLE DEFENSORES DEL 6 DE JUNIO SIN NUMERO, TEPEXI DE  RODRIGUEZ " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("e5f1bd4c-23dd-45a4-beb8-51579069b684"), Nombre = "UNIDAD DE INVESTIGACION TEPEYAHUALCO", Municipio = "TEPEYAHUALCO", Direccion = "CALLE PRIMERA DE VENUSTIANO CARRANZA Y CALLE PRIMERA MORELOS S/N TEPEYAHUALCO, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("e13e1af5-0f02-4f15-8607-f4b45d94b0c0"), Nombre = "UNIDAD DE INVESTIGACION TETELA DE OCAMPO", Municipio = "TETELA DE OCAMPO", Direccion = "7 PONIENTE #1, COLONIA CENTRO, TETELA DE OCAMPO, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("2698e8f1-6a18-4df2-919a-acb2f4ecf72d"), Nombre = "CASA DE JUSTICIA TEZIUTLÁN", Municipio = "TEZIUTLAN", Direccion = "CALLE LA MESILLA NO.10 COL. INDUSTRIAL, TEZIUTLÁN, PUEBLA. CP.: 73850" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("05f6286f-d7cc-4542-a83f-ba0833e8f1d6"), Nombre = "CENTRO INTEGRAL  DE SERVICIOS  TEZIUTLÁN ", Municipio = "TEZIUTLAN", Direccion = "AV HIDALGO NO.169 EDIFICIO REAL PLANTA BAJA, CENTRO. TEZIUTLAN, PUEBLA." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("b36b6895-a454-4783-a2bf-5440af2e518f"), Nombre = "AGENCIA ESTATAL DE INVESTIGACION", Municipio = "TEZIUTLAN", Direccion = "CALLE LERDO NÚMERO 205, ALTOS COL. CENTRO. ANEXO AL CERESO, TEZIUTLAN , PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("683c08ea-a693-4ec9-91c5-63c930e0e9ff"), Nombre = "SEMEFO TEZIUTLAN", Municipio = "TEZIUTLAN ", Direccion = "CALLE COSTADO SUR DEL PANTEON MUNICIPAL, SIN NUMERO, TEZIUTLAN, PUEBLA " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("40d44739-fb45-46c1-9d05-f18ed2e89d7d"), Nombre = "UNIDAD DE INVESTIGACION TLACOTEPEC", Municipio = "TLACOTEPEC DE BENITO JUAREZ", Direccion = "PLAZA COMUNITARIA CALLE AGUASCALIENTES SIN NUMERO COLONIA CENTRO 75680" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("0a40dfbd-a88e-4d5f-b295-d4a74ddf7f75"), Nombre = "UNIDAD DE INVESTIGACION TLALTENANGO ", Municipio = "TLALTENANGO", Direccion = "REAL DE SAN PEDRO NO 15 COL. CENTRO, C.P.72600, TLALTENANGO, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("1705e288-eb03-424e-af0c-b9f479f33d15"), Nombre = "UNIDAD DE INVESTIGACION TLAOLA", Municipio = "TLAOLA", Direccion = "ESQUINA QUE FORMAN LAS CALLES MORELOS Y CUAUHTEMOC NÚMERO 1, TLAOLA, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("aac51693-cc42-49e8-960b-579e9b468444"), Nombre = "UNIDAD DE INVESTIGACION TLAPANALA", Municipio = "TLAPANALA", Direccion = "PALACION MUNICIPAL S/N TLAPANALA PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("1f43c704-5596-4ded-a0b5-59d93fc19498"), Nombre = "CENTRO INTEGRAL DE SERVICIOS  TLATLAUQUITEPEC ", Municipio = "TLATLAUQUITEPEC", Direccion = "CARRETERA FEDERAL TEZIUTLAN - ACAJETE NO. 169 BARRIO DE CONTLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("f70ef1ad-0094-4119-8c6c-53399b848bcc"), Nombre = "AGENCIA ESTATAL DE INVESTIGACION", Municipio = "TLATLAUQUITEPEC", Direccion = "AV. INDEPENDENCIA NUM. 20 COL.CENTRO , TLATLAUQUITEPEC,PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("fea64774-60ed-4923-bb38-309168159be6"), Nombre = "SEMEFO TLATLAUQUITEPEC ", Municipio = "TLATLAUQUITEPEC", Direccion = "AV DOLORES BETANCOURT COL. CONTLA, TLATLAUQUITEPEC, PUEBLA " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("c00a403c-dd28-4684-8794-b8ea2c5bb364"), Nombre = "UNIDAD DE INVESTIGACION LAZARO CARDENAS", Municipio = "VILLA LAZARO CARDENAS", Direccion = "CARRETERA FEDERAL PACHUCA TUXPAN, COL. CENTRO, VILLA LÁZARO CARDENAS" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("1da44cbe-4719-4cc7-8103-ce7b9c853617"), Nombre = "CENTRO INTEGRAL SERVICIOS  XICOTEPEC DE JUAREZ", Municipio = "XICOTEPEC DE JUAREZ", Direccion = "CALLE FCO. JAVIER MINA NO. 303, COL. LA RIVERA XICOTEPEC DE JUAREZ, PUE. CP.: 73080" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("a4eced61-5cf3-4047-b6b5-ca7413f818c7"), Nombre = "UNIDAD DE INVESTIGACION XICOTEPEC DE JUAREZ", Municipio = "XICOTEPEC DE JUAREZ", Direccion = "CALLE 2 DE ABRIL 117 COLONIA CENTRO, XICOTEPEC DE JUAREZ, PUEBLA." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("8b820905-8270-44e7-afc0-13d9eabb77d5"), Nombre = "SEMEFO XICOTEPEC DE JUAREZ", Municipio = "XICOTEPEC DE JUAREZ", Direccion = "AV. ZARAGOZA SIN NUMERO, XICOTEPEC DE JUAREZ  " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("6b9fbf34-f812-4502-ac14-eff4c9241f47"), Nombre = "UNIDAD DE INVESTIGACION ZACAPOAXTLA", Municipio = "ZACAPOAXTLA", Direccion = "CALLE 2 DE ABRIL SUR, EDIFICIO REVOLUCIÓN ESQUINA IGNACIO COETO ,COL. CENTRO ZACAPOAXTLA PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("c09b9fdb-c701-455e-9122-646fe89d7561"), Nombre = "SEMEFO ZACAPOAXTLA ", Municipio = "ZACAPOAXTLA ", Direccion = "CALLE 2 DE ABRIL NORTE  SIN NUMERO ESQUINA FJ. ARRIAGA COL. CENTRO ZACAPOAXTLA, PUEBLA " });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("02d42a2c-869f-4a86-a656-61f5442a4d8c"), Nombre = "UNIDAD DE INVESTIGACIÓN CRIMINAL  Y UNIDAD DE ATENCIÓN TEMPRANA ZACATLAN", Municipio = "ZACATLAN", Direccion = "LIBRAMIENTO CARRETERA ZACATLAN -TEJOCOTAL, BARRIO DE MAQUIXTLA, ZACATLAN, PUEBLA CP.: 73310" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("967a8b5a-7e85-4cab-bc1c-365861402c87"), Nombre = "CENTRO INTEGRAL SERVICIOS ZACATLÁN ", Municipio = "ZACATLAN", Direccion = "COLONIA 2 CAMINOS ZACATLÁN , PUE. BARRIO TECOJOTAL, CP.: 73310" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("fdf2ff41-ab3f-4ea6-b116-fd40da4564f2"), Nombre = "SEMEFO ZACATLAN", Municipio = "ZACATLAN", Direccion = "CALLE PORFIRIO DIAZ Y DOLORES PEREZ SIN NUMERO COL. CENTRO  ZACATLAN, PUEBLA" });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("fed305e2-327f-4d6c-acb4-6f7eea552c76"), Nombre = "UNIDAD DE INVESTIGACION ZARAGOZA", Municipio = "ZARAGOZA", Direccion = "CALLE 3 ORIENTE 1211 COLONIA SANTA ANA, ZARAGOZA, PUE." });
            //modelBuilder.Entity<Inmueble>().HasData(new Inmueble { Id = new Guid("c013a797-be80-4f35-93ab-960194430f21"), Nombre = "UNIDAD DE INVESTIGACION ZOQUITLAN", Municipio = "ZOQUITLAN", Direccion = "CALLE JUVENTUD S/N COL. CENTRO" });
        }
    }
}
